/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "BuyDedicatedNumberInputObject.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

BuyDedicatedNumberInputObject::BuyDedicatedNumberInputObject()
{
    m_Phone = utility::conversions::to_string_t("");
    m_Country = utility::conversions::to_string_t("");
    m_UserId = 0;
}

BuyDedicatedNumberInputObject::~BuyDedicatedNumberInputObject()
{
}

void BuyDedicatedNumberInputObject::validate()
{
    // TODO: implement validation
}

web::json::value BuyDedicatedNumberInputObject::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("phone")] = ModelBase::toJson(m_Phone);
    val[utility::conversions::to_string_t("country")] = ModelBase::toJson(m_Country);
    val[utility::conversions::to_string_t("userId")] = ModelBase::toJson(m_UserId);

    return val;
}

void BuyDedicatedNumberInputObject::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("phone")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("phone")];
        if(!fieldValue.is_null())
        {
            setPhone(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("country")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("country")];
        if(!fieldValue.is_null())
        {
            setCountry(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("userId")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("userId")];
        if(!fieldValue.is_null())
        {
            setUserId(ModelBase::int32_tFromJson(fieldValue));
        }
    }
}

void BuyDedicatedNumberInputObject::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("phone"), m_Phone));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("country"), m_Country));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("userId"), m_UserId));
}

void BuyDedicatedNumberInputObject::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setPhone(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("phone"))));
    setCountry(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("country"))));
    setUserId(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("userId"))));
}

utility::string_t BuyDedicatedNumberInputObject::getPhone() const
{
    return m_Phone;
}


void BuyDedicatedNumberInputObject::setPhone(utility::string_t value)
{
    m_Phone = value;
    
}
utility::string_t BuyDedicatedNumberInputObject::getCountry() const
{
    return m_Country;
}


void BuyDedicatedNumberInputObject::setCountry(utility::string_t value)
{
    m_Country = value;
    
}
int32_t BuyDedicatedNumberInputObject::getUserId() const
{
    return m_UserId;
}


void BuyDedicatedNumberInputObject::setUserId(int32_t value)
{
    m_UserId = value;
    
}
}
}
}
}

