/**
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "EmailSenderItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

EmailSenderItem::EmailSenderItem()
{
    m_Id = 0;
    m_DomainId = 0;
    m_Email = utility::conversions::to_string_t("");
    m_CreatedAt = utility::datetime();
    m_DomainStatus = utility::conversions::to_string_t("");
    m_FromName = utility::conversions::to_string_t("");
    m_FromNameIsSet = false;
    m_ReplyTo = utility::conversions::to_string_t("");
    m_ReplyToIsSet = false;
}

EmailSenderItem::~EmailSenderItem()
{
}

void EmailSenderItem::validate()
{
    // TODO: implement validation
}

web::json::value EmailSenderItem::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    val[utility::conversions::to_string_t("domainId")] = ModelBase::toJson(m_DomainId);
    val[utility::conversions::to_string_t("email")] = ModelBase::toJson(m_Email);
    val[utility::conversions::to_string_t("createdAt")] = ModelBase::toJson(m_CreatedAt);
    val[utility::conversions::to_string_t("domainStatus")] = ModelBase::toJson(m_DomainStatus);
    if(m_FromNameIsSet)
    {
        val[utility::conversions::to_string_t("fromName")] = ModelBase::toJson(m_FromName);
    }
    if(m_ReplyToIsSet)
    {
        val[utility::conversions::to_string_t("replyTo")] = ModelBase::toJson(m_ReplyTo);
    }

    return val;
}

void EmailSenderItem::fromJson(web::json::value& val)
{
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("id")];
        if(!fieldValue.is_null())
        {
            setId(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("domainId")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("domainId")];
        if(!fieldValue.is_null())
        {
            setDomainId(ModelBase::int32_tFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("email")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("email")];
        if(!fieldValue.is_null())
        {
            setEmail(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("createdAt")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("createdAt")];
        if(!fieldValue.is_null())
        {
            setCreatedAt(ModelBase::dateFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("domainStatus")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("domainStatus")];
        if(!fieldValue.is_null())
        {
            setDomainStatus(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("fromName")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("fromName")];
        if(!fieldValue.is_null())
        {
            setFromName(ModelBase::stringFromJson(fieldValue));
        }
    }
    if(val.has_field(utility::conversions::to_string_t("replyTo")))
    {
        web::json::value& fieldValue = val[utility::conversions::to_string_t("replyTo")];
        if(!fieldValue.is_null())
        {
            setReplyTo(ModelBase::stringFromJson(fieldValue));
        }
    }
}

void EmailSenderItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("domainId"), m_DomainId));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("email"), m_Email));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("createdAt"), m_CreatedAt));
    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("domainStatus"), m_DomainStatus));
    if(m_FromNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("fromName"), m_FromName));
        
    }
    if(m_ReplyToIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("replyTo"), m_ReplyTo));
        
    }
}

void EmailSenderItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setId(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("id"))));
    setDomainId(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("domainId"))));
    setEmail(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("email"))));
    setCreatedAt(ModelBase::dateFromHttpContent(multipart->getContent(utility::conversions::to_string_t("createdAt"))));
    setDomainStatus(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("domainStatus"))));
    if(multipart->hasContent(utility::conversions::to_string_t("fromName")))
    {
        setFromName(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("fromName"))));
    }
    if(multipart->hasContent(utility::conversions::to_string_t("replyTo")))
    {
        setReplyTo(ModelBase::stringFromHttpContent(multipart->getContent(utility::conversions::to_string_t("replyTo"))));
    }
}

int32_t EmailSenderItem::getId() const
{
    return m_Id;
}


void EmailSenderItem::setId(int32_t value)
{
    m_Id = value;
    
}
int32_t EmailSenderItem::getDomainId() const
{
    return m_DomainId;
}


void EmailSenderItem::setDomainId(int32_t value)
{
    m_DomainId = value;
    
}
utility::string_t EmailSenderItem::getEmail() const
{
    return m_Email;
}


void EmailSenderItem::setEmail(utility::string_t value)
{
    m_Email = value;
    
}
utility::datetime EmailSenderItem::getCreatedAt() const
{
    return m_CreatedAt;
}


void EmailSenderItem::setCreatedAt(utility::datetime value)
{
    m_CreatedAt = value;
    
}
utility::string_t EmailSenderItem::getDomainStatus() const
{
    return m_DomainStatus;
}


void EmailSenderItem::setDomainStatus(utility::string_t value)
{
    m_DomainStatus = value;
    
}
utility::string_t EmailSenderItem::getFromName() const
{
    return m_FromName;
}


void EmailSenderItem::setFromName(utility::string_t value)
{
    m_FromName = value;
    m_FromNameIsSet = true;
}
bool EmailSenderItem::fromNameIsSet() const
{
    return m_FromNameIsSet;
}

void EmailSenderItem::unsetFromName()
{
    m_FromNameIsSet = false;
}

utility::string_t EmailSenderItem::getReplyTo() const
{
    return m_ReplyTo;
}


void EmailSenderItem::setReplyTo(utility::string_t value)
{
    m_ReplyTo = value;
    m_ReplyToIsSet = true;
}
bool EmailSenderItem::replyToIsSet() const
{
    return m_ReplyToIsSet;
}

void EmailSenderItem::unsetReplyTo()
{
    m_ReplyToIsSet = false;
}

}
}
}
}

