/**
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * File.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_File_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_File_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "FileMetadata.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  File
    : public ModelBase
{
public:
    File();
    virtual ~File();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// File members

    /// <summary>
    /// 
    /// </summary>
    int32_t getId() const;
        void setId(int32_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
        void setName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getOriginalName() const;
        void setOriginalName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMimeType() const;
        void setMimeType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getSize() const;
        void setSize(int32_t value);
    /// <summary>
    /// File type.
    /// </summary>
    utility::string_t getType() const;
        void setType(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::datetime getCreatedAt() const;
        void setCreatedAt(utility::datetime value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPreviewUrl() const;
    bool previewUrlIsSet() const;
    void unsetPreviewUrl();
    void setPreviewUrl(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();
    void setUrl(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<FileMetadata> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();
    void setMetadata(std::shared_ptr<FileMetadata> value);

protected:
    int32_t m_Id;
        utility::string_t m_Name;
        utility::string_t m_OriginalName;
        utility::string_t m_MimeType;
        int32_t m_Size;
        utility::string_t m_Type;
        utility::datetime m_CreatedAt;
        utility::string_t m_PreviewUrl;
    bool m_PreviewUrlIsSet;
    utility::string_t m_Url;
    bool m_UrlIsSet;
    std::shared_ptr<FileMetadata> m_Metadata;
    bool m_MetadataIsSet;
};

}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_File_H_ */
