/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/ContactCustomField.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

ContactCustomField::ContactCustomField()
{
    m_Value = utility::conversions::to_string_t("");
    m_ValueIsSet = false;
    m_UserCustomFieldIsSet = false;
}

ContactCustomField::~ContactCustomField()
{
}

void ContactCustomField::validate()
{
    // TODO: implement validation
}

web::json::value ContactCustomField::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ValueIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_UserCustomFieldIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("userCustomField"))] = ModelBase::toJson(m_UserCustomField);
    }

    return val;
}

bool ContactCustomField::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userCustomField"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userCustomField")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<UserCustomField> refVal_setUserCustomField;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserCustomField);
            setUserCustomField(refVal_setUserCustomField);
            
        }
    }
    return ok;
}

void ContactCustomField::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
    if(m_UserCustomFieldIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userCustomField")), m_UserCustomField));
    }
}

bool ContactCustomField::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        utility::string_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userCustomField"))))
    {
        std::shared_ptr<UserCustomField> refVal_setUserCustomField;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userCustomField"))), refVal_setUserCustomField );
        setUserCustomField(refVal_setUserCustomField);
    }
    return ok;
}


utility::string_t ContactCustomField::getValue() const
{
    return m_Value;
}


void ContactCustomField::setValue(const utility::string_t& value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool ContactCustomField::valueIsSet() const
{
    return m_ValueIsSet;
}

void ContactCustomField::unsetValue()
{
    m_ValueIsSet = false;
}
std::shared_ptr<UserCustomField> ContactCustomField::getUserCustomField() const
{
    return m_UserCustomField;
}


void ContactCustomField::setUserCustomField(const std::shared_ptr<UserCustomField>& value)
{
    m_UserCustomField = value;
    m_UserCustomFieldIsSet = true;
}

bool ContactCustomField::userCustomFieldIsSet() const
{
    return m_UserCustomFieldIsSet;
}

void ContactCustomField::unsetUserCustomField()
{
    m_UserCustomFieldIsSet = false;
}

}
}
}
}


