/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/CreateEmailCampaignResponse.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

CreateEmailCampaignResponse::CreateEmailCampaignResponse()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_StatusIsSet = false;
    m_EmailSenderId = 0;
    m_EmailSenderIdIsSet = false;
    m_StartAt = utility::datetime();
    m_StartAtIsSet = false;
    m_CreatedByIsSet = false;
    m_FromName = utility::conversions::to_string_t("");
    m_FromNameIsSet = false;
    m_FromEmail = utility::conversions::to_string_t("");
    m_FromEmailIsSet = false;
    m_ReplyToEmail = utility::conversions::to_string_t("");
    m_ReplyToEmailIsSet = false;
    m_Subject = utility::conversions::to_string_t("");
    m_SubjectIsSet = false;
    m_Html = utility::conversions::to_string_t("");
    m_HtmlIsSet = false;
    m_Cost = 0.0f;
    m_CostIsSet = false;
    m_TotalsIsSet = false;
    m_OutboundEmailIsSet = false;
    m_FailedReasonIsSet = false;
}

CreateEmailCampaignResponse::~CreateEmailCampaignResponse()
{
}

void CreateEmailCampaignResponse::validate()
{
    // TODO: implement validation
}

web::json::value CreateEmailCampaignResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_StatusIsSet)
    {   
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }
    if(m_EmailSenderIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("emailSenderId"))] = ModelBase::toJson(m_EmailSenderId);
    }
    if(m_StartAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("startAt"))] = ModelBase::toJson(m_StartAt);
    }
    if(m_CreatedByIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdBy"))] = ModelBase::toJson(m_CreatedBy);
    }
    if(m_FromNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("fromName"))] = ModelBase::toJson(m_FromName);
    }
    if(m_FromEmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("fromEmail"))] = ModelBase::toJson(m_FromEmail);
    }
    if(m_ReplyToEmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("replyToEmail"))] = ModelBase::toJson(m_ReplyToEmail);
    }
    if(m_SubjectIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("subject"))] = ModelBase::toJson(m_Subject);
    }
    if(m_HtmlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("html"))] = ModelBase::toJson(m_Html);
    }
    if(m_CostIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("cost"))] = ModelBase::toJson(m_Cost);
    }
    if(m_TotalsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("totals"))] = ModelBase::toJson(m_Totals);
    }
    if(m_OutboundEmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("outboundEmail"))] = ModelBase::toJson(m_OutboundEmail);
    }
    if(m_FailedReasonIsSet)
    {   
        
        utility::string_t refVal = fromFailedReasonEnum(m_FailedReason);
        val[utility::conversions::to_string_t(_XPLATSTR("failedReason"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool CreateEmailCampaignResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("emailSenderId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("emailSenderId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setEmailSenderId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailSenderId);
            setEmailSenderId(refVal_setEmailSenderId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("startAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("startAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setStartAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStartAt);
            setStartAt(refVal_setStartAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdBy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdBy")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<UserPersonalInfo> refVal_setCreatedBy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedBy);
            setCreatedBy(refVal_setCreatedBy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fromName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fromName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFromName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFromName);
            setFromName(refVal_setFromName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("fromEmail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("fromEmail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFromEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFromEmail);
            setFromEmail(refVal_setFromEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("replyToEmail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("replyToEmail")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setReplyToEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReplyToEmail);
            setReplyToEmail(refVal_setReplyToEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subject")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubject);
            setSubject(refVal_setSubject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("html"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("html")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHtml;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHtml);
            setHtml(refVal_setHtml);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cost"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cost")));
        if(!fieldValue.is_null())
        {
            float refVal_setCost;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCost);
            setCost(refVal_setCost);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totals"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totals")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<EmailCampaignStatisticTotals> refVal_setTotals;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotals);
            setTotals(refVal_setTotals);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("outboundEmail"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("outboundEmail")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<OutboundEmailResponse> refVal_setOutboundEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOutboundEmail);
            setOutboundEmail(refVal_setOutboundEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("failedReason"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("failedReason")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFailedReason;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFailedReason);
            
            setFailedReason(toFailedReasonEnum(refVal_setFailedReason));
            
        }
    }
    return ok;
}

void CreateEmailCampaignResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
    if(m_EmailSenderIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("emailSenderId")), m_EmailSenderId));
    }
    if(m_StartAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("startAt")), m_StartAt));
    }
    if(m_CreatedByIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdBy")), m_CreatedBy));
    }
    if(m_FromNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fromName")), m_FromName));
    }
    if(m_FromEmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("fromEmail")), m_FromEmail));
    }
    if(m_ReplyToEmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("replyToEmail")), m_ReplyToEmail));
    }
    if(m_SubjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subject")), m_Subject));
    }
    if(m_HtmlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("html")), m_Html));
    }
    if(m_CostIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cost")), m_Cost));
    }
    if(m_TotalsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totals")), m_Totals));
    }
    if(m_OutboundEmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("outboundEmail")), m_OutboundEmail));
    }
    if(m_FailedReasonIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("failedReason")), fromFailedReasonEnum(m_FailedReason)));
    }
}

bool CreateEmailCampaignResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("emailSenderId"))))
    {
        int32_t refVal_setEmailSenderId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("emailSenderId"))), refVal_setEmailSenderId );
        setEmailSenderId(refVal_setEmailSenderId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("startAt"))))
    {
        utility::datetime refVal_setStartAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("startAt"))), refVal_setStartAt );
        setStartAt(refVal_setStartAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdBy"))))
    {
        std::shared_ptr<UserPersonalInfo> refVal_setCreatedBy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdBy"))), refVal_setCreatedBy );
        setCreatedBy(refVal_setCreatedBy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fromName"))))
    {
        utility::string_t refVal_setFromName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fromName"))), refVal_setFromName );
        setFromName(refVal_setFromName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("fromEmail"))))
    {
        utility::string_t refVal_setFromEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("fromEmail"))), refVal_setFromEmail );
        setFromEmail(refVal_setFromEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("replyToEmail"))))
    {
        utility::string_t refVal_setReplyToEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("replyToEmail"))), refVal_setReplyToEmail );
        setReplyToEmail(refVal_setReplyToEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        utility::string_t refVal_setSubject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subject"))), refVal_setSubject );
        setSubject(refVal_setSubject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("html"))))
    {
        utility::string_t refVal_setHtml;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("html"))), refVal_setHtml );
        setHtml(refVal_setHtml);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cost"))))
    {
        float refVal_setCost;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cost"))), refVal_setCost );
        setCost(refVal_setCost);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totals"))))
    {
        std::shared_ptr<EmailCampaignStatisticTotals> refVal_setTotals;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totals"))), refVal_setTotals );
        setTotals(refVal_setTotals);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("outboundEmail"))))
    {
        std::shared_ptr<OutboundEmailResponse> refVal_setOutboundEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("outboundEmail"))), refVal_setOutboundEmail );
        setOutboundEmail(refVal_setOutboundEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("failedReason"))))
    {
        utility::string_t refVal_setFailedReason;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("failedReason"))), refVal_setFailedReason );
        setFailedReason(toFailedReasonEnum(refVal_setFailedReason));
    }
    return ok;
}

CreateEmailCampaignResponse::StatusEnum CreateEmailCampaignResponse::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("idle")) {
        return StatusEnum::IDLE;
    }
    
    if (value == utility::conversions::to_string_t("sent")) {
        return StatusEnum::SENT;
    }
    
    if (value == utility::conversions::to_string_t("in_progress")) {
        return StatusEnum::IN_PROGRESS;
    }
    
    if (value == utility::conversions::to_string_t("failed")) {
        return StatusEnum::FAILED;
    }
    
    if (value == utility::conversions::to_string_t("delivered")) {
        return StatusEnum::DELIVERED;
    }
    
    if (value == utility::conversions::to_string_t("rejected")) {
        return StatusEnum::REJECTED;
    }
    
    if (value == utility::conversions::to_string_t("error")) {
        return StatusEnum::ERROR;
    }
    
    if (value == utility::conversions::to_string_t("scheduledError")) {
        return StatusEnum::SCHEDULEDERROR;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t CreateEmailCampaignResponse::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::IDLE: return utility::conversions::to_string_t("idle");
        
        case StatusEnum::SENT: return utility::conversions::to_string_t("sent");
        
        case StatusEnum::IN_PROGRESS: return utility::conversions::to_string_t("in_progress");
        
        case StatusEnum::FAILED: return utility::conversions::to_string_t("failed");
        
        case StatusEnum::DELIVERED: return utility::conversions::to_string_t("delivered");
        
        case StatusEnum::REJECTED: return utility::conversions::to_string_t("rejected");
        
        case StatusEnum::ERROR: return utility::conversions::to_string_t("error");
        
        case StatusEnum::SCHEDULEDERROR: return utility::conversions::to_string_t("scheduledError");
        
    }
}

CreateEmailCampaignResponse::FailedReasonEnum CreateEmailCampaignResponse::toFailedReasonEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("lowBalance")) {
        return FailedReasonEnum::LOWBALANCE;
    }
    
    if (value == utility::conversions::to_string_t("noRecipients")) {
        return FailedReasonEnum::NORECIPIENTS;
    }
    
    if (value == utility::conversions::to_string_t("noEmailSender")) {
        return FailedReasonEnum::NOEMAILSENDER;
    }
    
    if (value == utility::conversions::to_string_t("unhandled")) {
        return FailedReasonEnum::UNHANDLED;
    }
    
    throw std::invalid_argument("Invalid value for conversion to FailedReasonEnum");
}


const utility::string_t CreateEmailCampaignResponse::fromFailedReasonEnum(const FailedReasonEnum value) const
{
    switch(value)
    {
        
        case FailedReasonEnum::LOWBALANCE: return utility::conversions::to_string_t("lowBalance");
        
        case FailedReasonEnum::NORECIPIENTS: return utility::conversions::to_string_t("noRecipients");
        
        case FailedReasonEnum::NOEMAILSENDER: return utility::conversions::to_string_t("noEmailSender");
        
        case FailedReasonEnum::UNHANDLED: return utility::conversions::to_string_t("unhandled");
        
    }
}


int32_t CreateEmailCampaignResponse::getId() const
{
    return m_Id;
}

void CreateEmailCampaignResponse::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CreateEmailCampaignResponse::idIsSet() const
{
    return m_IdIsSet;
}

void CreateEmailCampaignResponse::unsetId()
{
    m_IdIsSet = false;
}
CreateEmailCampaignResponse::StatusEnum CreateEmailCampaignResponse::getStatus() const
{
    return m_Status;
}


void CreateEmailCampaignResponse::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool CreateEmailCampaignResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void CreateEmailCampaignResponse::unsetStatus()
{
    m_StatusIsSet = false;
}
int32_t CreateEmailCampaignResponse::getEmailSenderId() const
{
    return m_EmailSenderId;
}

void CreateEmailCampaignResponse::setEmailSenderId(int32_t value)
{
    m_EmailSenderId = value;
    m_EmailSenderIdIsSet = true;
}

bool CreateEmailCampaignResponse::emailSenderIdIsSet() const
{
    return m_EmailSenderIdIsSet;
}

void CreateEmailCampaignResponse::unsetEmailSenderId()
{
    m_EmailSenderIdIsSet = false;
}
utility::datetime CreateEmailCampaignResponse::getStartAt() const
{
    return m_StartAt;
}


void CreateEmailCampaignResponse::setStartAt(const utility::datetime& value)
{
    m_StartAt = value;
    m_StartAtIsSet = true;
}

bool CreateEmailCampaignResponse::startAtIsSet() const
{
    return m_StartAtIsSet;
}

void CreateEmailCampaignResponse::unsetStartAt()
{
    m_StartAtIsSet = false;
}
std::shared_ptr<UserPersonalInfo> CreateEmailCampaignResponse::getCreatedBy() const
{
    return m_CreatedBy;
}


void CreateEmailCampaignResponse::setCreatedBy(const std::shared_ptr<UserPersonalInfo>& value)
{
    m_CreatedBy = value;
    m_CreatedByIsSet = true;
}

bool CreateEmailCampaignResponse::createdByIsSet() const
{
    return m_CreatedByIsSet;
}

void CreateEmailCampaignResponse::unsetCreatedBy()
{
    m_CreatedByIsSet = false;
}
utility::string_t CreateEmailCampaignResponse::getFromName() const
{
    return m_FromName;
}


void CreateEmailCampaignResponse::setFromName(const utility::string_t& value)
{
    m_FromName = value;
    m_FromNameIsSet = true;
}

bool CreateEmailCampaignResponse::fromNameIsSet() const
{
    return m_FromNameIsSet;
}

void CreateEmailCampaignResponse::unsetFromName()
{
    m_FromNameIsSet = false;
}
utility::string_t CreateEmailCampaignResponse::getFromEmail() const
{
    return m_FromEmail;
}


void CreateEmailCampaignResponse::setFromEmail(const utility::string_t& value)
{
    m_FromEmail = value;
    m_FromEmailIsSet = true;
}

bool CreateEmailCampaignResponse::fromEmailIsSet() const
{
    return m_FromEmailIsSet;
}

void CreateEmailCampaignResponse::unsetFromEmail()
{
    m_FromEmailIsSet = false;
}
utility::string_t CreateEmailCampaignResponse::getReplyToEmail() const
{
    return m_ReplyToEmail;
}


void CreateEmailCampaignResponse::setReplyToEmail(const utility::string_t& value)
{
    m_ReplyToEmail = value;
    m_ReplyToEmailIsSet = true;
}

bool CreateEmailCampaignResponse::replyToEmailIsSet() const
{
    return m_ReplyToEmailIsSet;
}

void CreateEmailCampaignResponse::unsetReplyToEmail()
{
    m_ReplyToEmailIsSet = false;
}
utility::string_t CreateEmailCampaignResponse::getSubject() const
{
    return m_Subject;
}


void CreateEmailCampaignResponse::setSubject(const utility::string_t& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}

bool CreateEmailCampaignResponse::subjectIsSet() const
{
    return m_SubjectIsSet;
}

void CreateEmailCampaignResponse::unsetSubject()
{
    m_SubjectIsSet = false;
}
utility::string_t CreateEmailCampaignResponse::getHtml() const
{
    return m_Html;
}


void CreateEmailCampaignResponse::setHtml(const utility::string_t& value)
{
    m_Html = value;
    m_HtmlIsSet = true;
}

bool CreateEmailCampaignResponse::htmlIsSet() const
{
    return m_HtmlIsSet;
}

void CreateEmailCampaignResponse::unsetHtml()
{
    m_HtmlIsSet = false;
}
float CreateEmailCampaignResponse::getCost() const
{
    return m_Cost;
}

void CreateEmailCampaignResponse::setCost(float value)
{
    m_Cost = value;
    m_CostIsSet = true;
}

bool CreateEmailCampaignResponse::costIsSet() const
{
    return m_CostIsSet;
}

void CreateEmailCampaignResponse::unsetCost()
{
    m_CostIsSet = false;
}
std::shared_ptr<EmailCampaignStatisticTotals> CreateEmailCampaignResponse::getTotals() const
{
    return m_Totals;
}


void CreateEmailCampaignResponse::setTotals(const std::shared_ptr<EmailCampaignStatisticTotals>& value)
{
    m_Totals = value;
    m_TotalsIsSet = true;
}

bool CreateEmailCampaignResponse::totalsIsSet() const
{
    return m_TotalsIsSet;
}

void CreateEmailCampaignResponse::unsetTotals()
{
    m_TotalsIsSet = false;
}
std::shared_ptr<OutboundEmailResponse> CreateEmailCampaignResponse::getOutboundEmail() const
{
    return m_OutboundEmail;
}


void CreateEmailCampaignResponse::setOutboundEmail(const std::shared_ptr<OutboundEmailResponse>& value)
{
    m_OutboundEmail = value;
    m_OutboundEmailIsSet = true;
}

bool CreateEmailCampaignResponse::outboundEmailIsSet() const
{
    return m_OutboundEmailIsSet;
}

void CreateEmailCampaignResponse::unsetOutboundEmail()
{
    m_OutboundEmailIsSet = false;
}
CreateEmailCampaignResponse::FailedReasonEnum CreateEmailCampaignResponse::getFailedReason() const
{
    return m_FailedReason;
}


void CreateEmailCampaignResponse::setFailedReason(const FailedReasonEnum value)
{
    m_FailedReason = value;
    m_FailedReasonIsSet = true;
}

bool CreateEmailCampaignResponse::failedReasonIsSet() const
{
    return m_FailedReasonIsSet;
}

void CreateEmailCampaignResponse::unsetFailedReason()
{
    m_FailedReasonIsSet = false;
}

}
}
}
}


