/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/Currency.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

Currency::Currency()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_UnicodeSymbol = utility::conversions::to_string_t("");
    m_UnicodeSymbolIsSet = false;
    m_HtmlSymbol = utility::conversions::to_string_t("");
    m_HtmlSymbolIsSet = false;
}

Currency::~Currency()
{
}

void Currency::validate()
{
    // TODO: implement validation
}

web::json::value Currency::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UnicodeSymbolIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol"))] = ModelBase::toJson(m_UnicodeSymbol);
    }
    if(m_HtmlSymbolIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("htmlSymbol"))] = ModelBase::toJson(m_HtmlSymbol);
    }

    return val;
}

bool Currency::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUnicodeSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnicodeSymbol);
            setUnicodeSymbol(refVal_setUnicodeSymbol);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("htmlSymbol"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("htmlSymbol")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHtmlSymbol;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHtmlSymbol);
            setHtmlSymbol(refVal_setHtmlSymbol);
            
        }
    }
    return ok;
}

void Currency::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_UnicodeSymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol")), m_UnicodeSymbol));
    }
    if(m_HtmlSymbolIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("htmlSymbol")), m_HtmlSymbol));
    }
}

bool Currency::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol"))))
    {
        utility::string_t refVal_setUnicodeSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("unicodeSymbol"))), refVal_setUnicodeSymbol );
        setUnicodeSymbol(refVal_setUnicodeSymbol);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("htmlSymbol"))))
    {
        utility::string_t refVal_setHtmlSymbol;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("htmlSymbol"))), refVal_setHtmlSymbol );
        setHtmlSymbol(refVal_setHtmlSymbol);
    }
    return ok;
}


utility::string_t Currency::getId() const
{
    return m_Id;
}


void Currency::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Currency::idIsSet() const
{
    return m_IdIsSet;
}

void Currency::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Currency::getUnicodeSymbol() const
{
    return m_UnicodeSymbol;
}


void Currency::setUnicodeSymbol(const utility::string_t& value)
{
    m_UnicodeSymbol = value;
    m_UnicodeSymbolIsSet = true;
}

bool Currency::unicodeSymbolIsSet() const
{
    return m_UnicodeSymbolIsSet;
}

void Currency::unsetUnicodeSymbol()
{
    m_UnicodeSymbolIsSet = false;
}
utility::string_t Currency::getHtmlSymbol() const
{
    return m_HtmlSymbol;
}


void Currency::setHtmlSymbol(const utility::string_t& value)
{
    m_HtmlSymbol = value;
    m_HtmlSymbolIsSet = true;
}

bool Currency::htmlSymbolIsSet() const
{
    return m_HtmlSymbolIsSet;
}

void Currency::unsetHtmlSymbol()
{
    m_HtmlSymbolIsSet = false;
}

}
}
}
}


