/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/CustomFieldListItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

CustomFieldListItem::CustomFieldListItem()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_UserCustomFieldId = 0;
    m_UserCustomFieldIdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Value = utility::conversions::to_string_t("");
    m_ValueIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
}

CustomFieldListItem::~CustomFieldListItem()
{
}

void CustomFieldListItem::validate()
{
    // TODO: implement validation
}

web::json::value CustomFieldListItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UserCustomFieldIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId"))] = ModelBase::toJson(m_UserCustomFieldId);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_ValueIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_CreatedAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }

    return val;
}

bool CustomFieldListItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setUserCustomFieldId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserCustomFieldId);
            setUserCustomFieldId(refVal_setUserCustomFieldId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    return ok;
}

void CustomFieldListItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_UserCustomFieldIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId")), m_UserCustomFieldId));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
}

bool CustomFieldListItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId"))))
    {
        int32_t refVal_setUserCustomFieldId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userCustomFieldId"))), refVal_setUserCustomFieldId );
        setUserCustomFieldId(refVal_setUserCustomFieldId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        utility::string_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    return ok;
}


int32_t CustomFieldListItem::getId() const
{
    return m_Id;
}

void CustomFieldListItem::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool CustomFieldListItem::idIsSet() const
{
    return m_IdIsSet;
}

void CustomFieldListItem::unsetId()
{
    m_IdIsSet = false;
}
int32_t CustomFieldListItem::getUserCustomFieldId() const
{
    return m_UserCustomFieldId;
}

void CustomFieldListItem::setUserCustomFieldId(int32_t value)
{
    m_UserCustomFieldId = value;
    m_UserCustomFieldIdIsSet = true;
}

bool CustomFieldListItem::userCustomFieldIdIsSet() const
{
    return m_UserCustomFieldIdIsSet;
}

void CustomFieldListItem::unsetUserCustomFieldId()
{
    m_UserCustomFieldIdIsSet = false;
}
utility::string_t CustomFieldListItem::getName() const
{
    return m_Name;
}


void CustomFieldListItem::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool CustomFieldListItem::nameIsSet() const
{
    return m_NameIsSet;
}

void CustomFieldListItem::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t CustomFieldListItem::getValue() const
{
    return m_Value;
}


void CustomFieldListItem::setValue(const utility::string_t& value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool CustomFieldListItem::valueIsSet() const
{
    return m_ValueIsSet;
}

void CustomFieldListItem::unsetValue()
{
    m_ValueIsSet = false;
}
utility::datetime CustomFieldListItem::getCreatedAt() const
{
    return m_CreatedAt;
}


void CustomFieldListItem::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool CustomFieldListItem::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void CustomFieldListItem::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}

}
}
}
}


