/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/File.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

File::File()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_OriginalName = utility::conversions::to_string_t("");
    m_OriginalNameIsSet = false;
    m_MimeType = utility::conversions::to_string_t("");
    m_MimeTypeIsSet = false;
    m_Size = 0;
    m_SizeIsSet = false;
    m_TypeIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
    m_PreviewUrl = utility::conversions::to_string_t("");
    m_PreviewUrlIsSet = false;
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_MetadataIsSet = false;
}

File::~File()
{
}

void File::validate()
{
    // TODO: implement validation
}

web::json::value File::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_OriginalNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("originalName"))] = ModelBase::toJson(m_OriginalName);
    }
    if(m_MimeTypeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("mimeType"))] = ModelBase::toJson(m_MimeType);
    }
    if(m_SizeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("size"))] = ModelBase::toJson(m_Size);
    }
    if(m_TypeIsSet)
    {   
        
        utility::string_t refVal = fromTypeEnum(m_Type);
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(refVal);
        
    }
    if(m_CreatedAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }
    if(m_PreviewUrlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("previewUrl"))] = ModelBase::toJson(m_PreviewUrl);
    }
    if(m_UrlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("url"))] = ModelBase::toJson(m_Url);
    }
    if(m_MetadataIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("metadata"))] = ModelBase::toJson(m_Metadata);
    }

    return val;
}

bool File::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("originalName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("originalName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOriginalName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOriginalName);
            setOriginalName(refVal_setOriginalName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mimeType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mimeType")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMimeType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMimeType);
            setMimeType(refVal_setMimeType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSize);
            setSize(refVal_setSize);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            
            setType(toTypeEnum(refVal_setType));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("previewUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("previewUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPreviewUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPreviewUrl);
            setPreviewUrl(refVal_setPreviewUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("metadata")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<FileMetadata> refVal_setMetadata;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMetadata);
            setMetadata(refVal_setMetadata);
            
        }
    }
    return ok;
}

void File::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_OriginalNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("originalName")), m_OriginalName));
    }
    if(m_MimeTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mimeType")), m_MimeType));
    }
    if(m_SizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("size")), m_Size));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), fromTypeEnum(m_Type)));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
    if(m_PreviewUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("previewUrl")), m_PreviewUrl));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("url")), m_Url));
    }
    if(m_MetadataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("metadata")), m_Metadata));
    }
}

bool File::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("originalName"))))
    {
        utility::string_t refVal_setOriginalName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("originalName"))), refVal_setOriginalName );
        setOriginalName(refVal_setOriginalName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mimeType"))))
    {
        utility::string_t refVal_setMimeType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mimeType"))), refVal_setMimeType );
        setMimeType(refVal_setMimeType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("size"))))
    {
        int32_t refVal_setSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("size"))), refVal_setSize );
        setSize(refVal_setSize);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(toTypeEnum(refVal_setType));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("previewUrl"))))
    {
        utility::string_t refVal_setPreviewUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("previewUrl"))), refVal_setPreviewUrl );
        setPreviewUrl(refVal_setPreviewUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))))
    {
        std::shared_ptr<FileMetadata> refVal_setMetadata;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("metadata"))), refVal_setMetadata );
        setMetadata(refVal_setMetadata);
    }
    return ok;
}

File::TypeEnum File::toTypeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("attachment")) {
        return TypeEnum::ATTACHMENT;
    }
    
    if (value == utility::conversions::to_string_t("import")) {
        return TypeEnum::IMPORT;
    }
    
    if (value == utility::conversions::to_string_t("raw_email")) {
        return TypeEnum::RAW_EMAIL;
    }
    
    if (value == utility::conversions::to_string_t("inline_attachment")) {
        return TypeEnum::INLINE_ATTACHMENT;
    }
    
    if (value == utility::conversions::to_string_t("chat-attachment")) {
        return TypeEnum::CHAT_ATTACHMENT;
    }
    
    if (value == utility::conversions::to_string_t("knowledge_base")) {
        return TypeEnum::KNOWLEDGE_BASE;
    }
    
    if (value == utility::conversions::to_string_t("facebook_page_picture")) {
        return TypeEnum::FACEBOOK_PAGE_PICTURE;
    }
    
    if (value == utility::conversions::to_string_t("instagram_account_picture")) {
        return TypeEnum::INSTAGRAM_ACCOUNT_PICTURE;
    }
    
    if (value == utility::conversions::to_string_t("logo")) {
        return TypeEnum::LOGO;
    }
    
    throw std::invalid_argument("Invalid value for conversion to TypeEnum");
}


const utility::string_t File::fromTypeEnum(const TypeEnum value) const
{
    switch(value)
    {
        
        case TypeEnum::ATTACHMENT: return utility::conversions::to_string_t("attachment");
        
        case TypeEnum::IMPORT: return utility::conversions::to_string_t("import");
        
        case TypeEnum::RAW_EMAIL: return utility::conversions::to_string_t("raw_email");
        
        case TypeEnum::INLINE_ATTACHMENT: return utility::conversions::to_string_t("inline_attachment");
        
        case TypeEnum::CHAT_ATTACHMENT: return utility::conversions::to_string_t("chat-attachment");
        
        case TypeEnum::KNOWLEDGE_BASE: return utility::conversions::to_string_t("knowledge_base");
        
        case TypeEnum::FACEBOOK_PAGE_PICTURE: return utility::conversions::to_string_t("facebook_page_picture");
        
        case TypeEnum::INSTAGRAM_ACCOUNT_PICTURE: return utility::conversions::to_string_t("instagram_account_picture");
        
        case TypeEnum::LOGO: return utility::conversions::to_string_t("logo");
        
    }
}


int32_t File::getId() const
{
    return m_Id;
}

void File::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool File::idIsSet() const
{
    return m_IdIsSet;
}

void File::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t File::getName() const
{
    return m_Name;
}


void File::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool File::nameIsSet() const
{
    return m_NameIsSet;
}

void File::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t File::getOriginalName() const
{
    return m_OriginalName;
}


void File::setOriginalName(const utility::string_t& value)
{
    m_OriginalName = value;
    m_OriginalNameIsSet = true;
}

bool File::originalNameIsSet() const
{
    return m_OriginalNameIsSet;
}

void File::unsetOriginalName()
{
    m_OriginalNameIsSet = false;
}
utility::string_t File::getMimeType() const
{
    return m_MimeType;
}


void File::setMimeType(const utility::string_t& value)
{
    m_MimeType = value;
    m_MimeTypeIsSet = true;
}

bool File::mimeTypeIsSet() const
{
    return m_MimeTypeIsSet;
}

void File::unsetMimeType()
{
    m_MimeTypeIsSet = false;
}
int32_t File::getSize() const
{
    return m_Size;
}

void File::setSize(int32_t value)
{
    m_Size = value;
    m_SizeIsSet = true;
}

bool File::sizeIsSet() const
{
    return m_SizeIsSet;
}

void File::unsetSize()
{
    m_SizeIsSet = false;
}
File::TypeEnum File::getType() const
{
    return m_Type;
}


void File::setType(const TypeEnum value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool File::typeIsSet() const
{
    return m_TypeIsSet;
}

void File::unsetType()
{
    m_TypeIsSet = false;
}
utility::datetime File::getCreatedAt() const
{
    return m_CreatedAt;
}


void File::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool File::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void File::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}
utility::string_t File::getPreviewUrl() const
{
    return m_PreviewUrl;
}


void File::setPreviewUrl(const utility::string_t& value)
{
    m_PreviewUrl = value;
    m_PreviewUrlIsSet = true;
}

bool File::previewUrlIsSet() const
{
    return m_PreviewUrlIsSet;
}

void File::unsetPreviewUrl()
{
    m_PreviewUrlIsSet = false;
}
utility::string_t File::getUrl() const
{
    return m_Url;
}


void File::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool File::urlIsSet() const
{
    return m_UrlIsSet;
}

void File::unsetUrl()
{
    m_UrlIsSet = false;
}
std::shared_ptr<FileMetadata> File::getMetadata() const
{
    return m_Metadata;
}


void File::setMetadata(const std::shared_ptr<FileMetadata>& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}

bool File::metadataIsSet() const
{
    return m_MetadataIsSet;
}

void File::unsetMetadata()
{
    m_MetadataIsSet = false;
}

}
}
}
}


