/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/GetMessagePriceResponseCountriesItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

GetMessagePriceResponseCountriesItem::GetMessagePriceResponseCountriesItem()
{
    m_Country = utility::conversions::to_string_t("");
    m_CountryIsSet = false;
    m_CountryName = utility::conversions::to_string_t("");
    m_CountryNameIsSet = false;
    m_AllowDedicated = false;
    m_AllowDedicatedIsSet = false;
    m_Count = 0.0;
    m_CountIsSet = false;
    m_Max = 0.0;
    m_MaxIsSet = false;
    m_Sum = utility::conversions::to_string_t("");
    m_SumIsSet = false;
    m_Landline = 0.0;
    m_LandlineIsSet = false;
}

GetMessagePriceResponseCountriesItem::~GetMessagePriceResponseCountriesItem()
{
}

void GetMessagePriceResponseCountriesItem::validate()
{
    // TODO: implement validation
}

web::json::value GetMessagePriceResponseCountriesItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CountryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country);
    }
    if(m_CountryNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("countryName"))] = ModelBase::toJson(m_CountryName);
    }
    if(m_AllowDedicatedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("allowDedicated"))] = ModelBase::toJson(m_AllowDedicated);
    }
    if(m_CountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("count"))] = ModelBase::toJson(m_Count);
    }
    if(m_MaxIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("max"))] = ModelBase::toJson(m_Max);
    }
    if(m_SumIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("sum"))] = ModelBase::toJson(m_Sum);
    }
    if(m_LandlineIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("landline"))] = ModelBase::toJson(m_Landline);
    }

    return val;
}

bool GetMessagePriceResponseCountriesItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("countryName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("countryName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountryName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountryName);
            setCountryName(refVal_setCountryName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("allowDedicated"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("allowDedicated")));
        if(!fieldValue.is_null())
        {
            bool refVal_setAllowDedicated;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAllowDedicated);
            setAllowDedicated(refVal_setAllowDedicated);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("count")));
        if(!fieldValue.is_null())
        {
            double refVal_setCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCount);
            setCount(refVal_setCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("max"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("max")));
        if(!fieldValue.is_null())
        {
            double refVal_setMax;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMax);
            setMax(refVal_setMax);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sum"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sum")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSum;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSum);
            setSum(refVal_setSum);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("landline"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("landline")));
        if(!fieldValue.is_null())
        {
            double refVal_setLandline;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLandline);
            setLandline(refVal_setLandline);
            
        }
    }
    return ok;
}

void GetMessagePriceResponseCountriesItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CountryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country));
    }
    if(m_CountryNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("countryName")), m_CountryName));
    }
    if(m_AllowDedicatedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("allowDedicated")), m_AllowDedicated));
    }
    if(m_CountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("count")), m_Count));
    }
    if(m_MaxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("max")), m_Max));
    }
    if(m_SumIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sum")), m_Sum));
    }
    if(m_LandlineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("landline")), m_Landline));
    }
}

bool GetMessagePriceResponseCountriesItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("countryName"))))
    {
        utility::string_t refVal_setCountryName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("countryName"))), refVal_setCountryName );
        setCountryName(refVal_setCountryName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("allowDedicated"))))
    {
        bool refVal_setAllowDedicated;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("allowDedicated"))), refVal_setAllowDedicated );
        setAllowDedicated(refVal_setAllowDedicated);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("count"))))
    {
        double refVal_setCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("count"))), refVal_setCount );
        setCount(refVal_setCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("max"))))
    {
        double refVal_setMax;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("max"))), refVal_setMax );
        setMax(refVal_setMax);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sum"))))
    {
        utility::string_t refVal_setSum;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sum"))), refVal_setSum );
        setSum(refVal_setSum);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("landline"))))
    {
        double refVal_setLandline;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("landline"))), refVal_setLandline );
        setLandline(refVal_setLandline);
    }
    return ok;
}


utility::string_t GetMessagePriceResponseCountriesItem::getCountry() const
{
    return m_Country;
}


void GetMessagePriceResponseCountriesItem::setCountry(const utility::string_t& value)
{
    m_Country = value;
    m_CountryIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::countryIsSet() const
{
    return m_CountryIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetCountry()
{
    m_CountryIsSet = false;
}
utility::string_t GetMessagePriceResponseCountriesItem::getCountryName() const
{
    return m_CountryName;
}


void GetMessagePriceResponseCountriesItem::setCountryName(const utility::string_t& value)
{
    m_CountryName = value;
    m_CountryNameIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::countryNameIsSet() const
{
    return m_CountryNameIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetCountryName()
{
    m_CountryNameIsSet = false;
}
bool GetMessagePriceResponseCountriesItem::isAllowDedicated() const
{
    return m_AllowDedicated;
}

void GetMessagePriceResponseCountriesItem::setAllowDedicated(bool value)
{
    m_AllowDedicated = value;
    m_AllowDedicatedIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::allowDedicatedIsSet() const
{
    return m_AllowDedicatedIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetAllowDedicated()
{
    m_AllowDedicatedIsSet = false;
}
double GetMessagePriceResponseCountriesItem::getCount() const
{
    return m_Count;
}

void GetMessagePriceResponseCountriesItem::setCount(double value)
{
    m_Count = value;
    m_CountIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::countIsSet() const
{
    return m_CountIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetCount()
{
    m_CountIsSet = false;
}
double GetMessagePriceResponseCountriesItem::getMax() const
{
    return m_Max;
}

void GetMessagePriceResponseCountriesItem::setMax(double value)
{
    m_Max = value;
    m_MaxIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::maxIsSet() const
{
    return m_MaxIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetMax()
{
    m_MaxIsSet = false;
}
utility::string_t GetMessagePriceResponseCountriesItem::getSum() const
{
    return m_Sum;
}


void GetMessagePriceResponseCountriesItem::setSum(const utility::string_t& value)
{
    m_Sum = value;
    m_SumIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::sumIsSet() const
{
    return m_SumIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetSum()
{
    m_SumIsSet = false;
}
double GetMessagePriceResponseCountriesItem::getLandline() const
{
    return m_Landline;
}

void GetMessagePriceResponseCountriesItem::setLandline(double value)
{
    m_Landline = value;
    m_LandlineIsSet = true;
}

bool GetMessagePriceResponseCountriesItem::landlineIsSet() const
{
    return m_LandlineIsSet;
}

void GetMessagePriceResponseCountriesItem::unsetLandline()
{
    m_LandlineIsSet = false;
}

}
}
}
}


