/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/GetOutboundMessagesHistoryPaginatedResponse.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

GetOutboundMessagesHistoryPaginatedResponse::GetOutboundMessagesHistoryPaginatedResponse()
{
    m_LastId = 0;
    m_LastIdIsSet = false;
    m_NextLastId = 0;
    m_NextLastIdIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_ResourcesIsSet = false;
}

GetOutboundMessagesHistoryPaginatedResponse::~GetOutboundMessagesHistoryPaginatedResponse()
{
}

void GetOutboundMessagesHistoryPaginatedResponse::validate()
{
    // TODO: implement validation
}

web::json::value GetOutboundMessagesHistoryPaginatedResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_LastIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastId"))] = ModelBase::toJson(m_LastId);
    }
    if(m_NextLastIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("nextLastId"))] = ModelBase::toJson(m_NextLastId);
    }
    if(m_LimitIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_ResourcesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("resources"))] = ModelBase::toJson(m_Resources);
    }

    return val;
}

bool GetOutboundMessagesHistoryPaginatedResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLastId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastId);
            setLastId(refVal_setLastId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("nextLastId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("nextLastId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNextLastId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNextLastId);
            setNextLastId(refVal_setNextLastId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("resources"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("resources")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<MessageOut>> refVal_setResources;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResources);
            setResources(refVal_setResources);
            
        }
    }
    return ok;
}

void GetOutboundMessagesHistoryPaginatedResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_LastIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastId")), m_LastId));
    }
    if(m_NextLastIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("nextLastId")), m_NextLastId));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limit")), m_Limit));
    }
    if(m_ResourcesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("resources")), m_Resources));
    }
}

bool GetOutboundMessagesHistoryPaginatedResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastId"))))
    {
        int32_t refVal_setLastId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastId"))), refVal_setLastId );
        setLastId(refVal_setLastId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("nextLastId"))))
    {
        int32_t refVal_setNextLastId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("nextLastId"))), refVal_setNextLastId );
        setNextLastId(refVal_setNextLastId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("resources"))))
    {
        std::vector<std::shared_ptr<MessageOut>> refVal_setResources;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("resources"))), refVal_setResources );
        setResources(refVal_setResources);
    }
    return ok;
}


int32_t GetOutboundMessagesHistoryPaginatedResponse::getLastId() const
{
    return m_LastId;
}

void GetOutboundMessagesHistoryPaginatedResponse::setLastId(int32_t value)
{
    m_LastId = value;
    m_LastIdIsSet = true;
}

bool GetOutboundMessagesHistoryPaginatedResponse::lastIdIsSet() const
{
    return m_LastIdIsSet;
}

void GetOutboundMessagesHistoryPaginatedResponse::unsetLastId()
{
    m_LastIdIsSet = false;
}
int32_t GetOutboundMessagesHistoryPaginatedResponse::getNextLastId() const
{
    return m_NextLastId;
}

void GetOutboundMessagesHistoryPaginatedResponse::setNextLastId(int32_t value)
{
    m_NextLastId = value;
    m_NextLastIdIsSet = true;
}

bool GetOutboundMessagesHistoryPaginatedResponse::nextLastIdIsSet() const
{
    return m_NextLastIdIsSet;
}

void GetOutboundMessagesHistoryPaginatedResponse::unsetNextLastId()
{
    m_NextLastIdIsSet = false;
}
int32_t GetOutboundMessagesHistoryPaginatedResponse::getLimit() const
{
    return m_Limit;
}

void GetOutboundMessagesHistoryPaginatedResponse::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool GetOutboundMessagesHistoryPaginatedResponse::limitIsSet() const
{
    return m_LimitIsSet;
}

void GetOutboundMessagesHistoryPaginatedResponse::unsetLimit()
{
    m_LimitIsSet = false;
}
std::vector<std::shared_ptr<MessageOut>> GetOutboundMessagesHistoryPaginatedResponse::getResources() const
{
    return m_Resources;
}


void GetOutboundMessagesHistoryPaginatedResponse::setResources(const std::vector<std::shared_ptr<MessageOut>>& value)
{
    m_Resources = value;
    m_ResourcesIsSet = true;
}

bool GetOutboundMessagesHistoryPaginatedResponse::resourcesIsSet() const
{
    return m_ResourcesIsSet;
}

void GetOutboundMessagesHistoryPaginatedResponse::unsetResources()
{
    m_ResourcesIsSet = false;
}

}
}
}
}


