/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/GetSubaccountsWithTokens_request.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

GetSubaccountsWithTokens_request::GetSubaccountsWithTokens_request()
{
    m_AppName = utility::conversions::to_string_t("");
    m_AppNameIsSet = false;
    m_Password = utility::conversions::to_string_t("");
    m_PasswordIsSet = false;
}

GetSubaccountsWithTokens_request::~GetSubaccountsWithTokens_request()
{
}

void GetSubaccountsWithTokens_request::validate()
{
    // TODO: implement validation
}

web::json::value GetSubaccountsWithTokens_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AppNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("appName"))] = ModelBase::toJson(m_AppName);
    }
    if(m_PasswordIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("password"))] = ModelBase::toJson(m_Password);
    }

    return val;
}

bool GetSubaccountsWithTokens_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("appName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("appName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAppName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAppName);
            setAppName(refVal_setAppName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("password"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("password")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPassword;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPassword);
            setPassword(refVal_setPassword);
            
        }
    }
    return ok;
}

void GetSubaccountsWithTokens_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AppNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("appName")), m_AppName));
    }
    if(m_PasswordIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("password")), m_Password));
    }
}

bool GetSubaccountsWithTokens_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("appName"))))
    {
        utility::string_t refVal_setAppName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("appName"))), refVal_setAppName );
        setAppName(refVal_setAppName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("password"))))
    {
        utility::string_t refVal_setPassword;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("password"))), refVal_setPassword );
        setPassword(refVal_setPassword);
    }
    return ok;
}


utility::string_t GetSubaccountsWithTokens_request::getAppName() const
{
    return m_AppName;
}


void GetSubaccountsWithTokens_request::setAppName(const utility::string_t& value)
{
    m_AppName = value;
    m_AppNameIsSet = true;
}

bool GetSubaccountsWithTokens_request::appNameIsSet() const
{
    return m_AppNameIsSet;
}

void GetSubaccountsWithTokens_request::unsetAppName()
{
    m_AppNameIsSet = false;
}
utility::string_t GetSubaccountsWithTokens_request::getPassword() const
{
    return m_Password;
}


void GetSubaccountsWithTokens_request::setPassword(const utility::string_t& value)
{
    m_Password = value;
    m_PasswordIsSet = true;
}

bool GetSubaccountsWithTokens_request::passwordIsSet() const
{
    return m_PasswordIsSet;
}

void GetSubaccountsWithTokens_request::unsetPassword()
{
    m_PasswordIsSet = false;
}

}
}
}
}


