/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/GetUnsubscribersPaginatedResponse.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

GetUnsubscribersPaginatedResponse::GetUnsubscribersPaginatedResponse()
{
    m_Page = 0;
    m_PageIsSet = false;
    m_PageCount = 0;
    m_PageCountIsSet = false;
    m_Limit = 0;
    m_LimitIsSet = false;
    m_ResourcesIsSet = false;
}

GetUnsubscribersPaginatedResponse::~GetUnsubscribersPaginatedResponse()
{
}

void GetUnsubscribersPaginatedResponse::validate()
{
    // TODO: implement validation
}

web::json::value GetUnsubscribersPaginatedResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PageIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("page"))] = ModelBase::toJson(m_Page);
    }
    if(m_PageCountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("pageCount"))] = ModelBase::toJson(m_PageCount);
    }
    if(m_LimitIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("limit"))] = ModelBase::toJson(m_Limit);
    }
    if(m_ResourcesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("resources"))] = ModelBase::toJson(m_Resources);
    }

    return val;
}

bool GetUnsubscribersPaginatedResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("page"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("page")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPage);
            setPage(refVal_setPage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("pageCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("pageCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPageCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPageCount);
            setPageCount(refVal_setPageCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("limit")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLimit);
            setLimit(refVal_setLimit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("resources"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("resources")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<UnsubscribedContact>> refVal_setResources;
            ok &= ModelBase::fromJson(fieldValue, refVal_setResources);
            setResources(refVal_setResources);
            
        }
    }
    return ok;
}

void GetUnsubscribersPaginatedResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("page")), m_Page));
    }
    if(m_PageCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("pageCount")), m_PageCount));
    }
    if(m_LimitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("limit")), m_Limit));
    }
    if(m_ResourcesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("resources")), m_Resources));
    }
}

bool GetUnsubscribersPaginatedResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("page"))))
    {
        int32_t refVal_setPage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("page"))), refVal_setPage );
        setPage(refVal_setPage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("pageCount"))))
    {
        int32_t refVal_setPageCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("pageCount"))), refVal_setPageCount );
        setPageCount(refVal_setPageCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("limit"))))
    {
        int32_t refVal_setLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("limit"))), refVal_setLimit );
        setLimit(refVal_setLimit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("resources"))))
    {
        std::vector<std::shared_ptr<UnsubscribedContact>> refVal_setResources;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("resources"))), refVal_setResources );
        setResources(refVal_setResources);
    }
    return ok;
}


int32_t GetUnsubscribersPaginatedResponse::getPage() const
{
    return m_Page;
}

void GetUnsubscribersPaginatedResponse::setPage(int32_t value)
{
    m_Page = value;
    m_PageIsSet = true;
}

bool GetUnsubscribersPaginatedResponse::pageIsSet() const
{
    return m_PageIsSet;
}

void GetUnsubscribersPaginatedResponse::unsetPage()
{
    m_PageIsSet = false;
}
int32_t GetUnsubscribersPaginatedResponse::getPageCount() const
{
    return m_PageCount;
}

void GetUnsubscribersPaginatedResponse::setPageCount(int32_t value)
{
    m_PageCount = value;
    m_PageCountIsSet = true;
}

bool GetUnsubscribersPaginatedResponse::pageCountIsSet() const
{
    return m_PageCountIsSet;
}

void GetUnsubscribersPaginatedResponse::unsetPageCount()
{
    m_PageCountIsSet = false;
}
int32_t GetUnsubscribersPaginatedResponse::getLimit() const
{
    return m_Limit;
}

void GetUnsubscribersPaginatedResponse::setLimit(int32_t value)
{
    m_Limit = value;
    m_LimitIsSet = true;
}

bool GetUnsubscribersPaginatedResponse::limitIsSet() const
{
    return m_LimitIsSet;
}

void GetUnsubscribersPaginatedResponse::unsetLimit()
{
    m_LimitIsSet = false;
}
std::vector<std::shared_ptr<UnsubscribedContact>> GetUnsubscribersPaginatedResponse::getResources() const
{
    return m_Resources;
}


void GetUnsubscribersPaginatedResponse::setResources(const std::vector<std::shared_ptr<UnsubscribedContact>>& value)
{
    m_Resources = value;
    m_ResourcesIsSet = true;
}

bool GetUnsubscribersPaginatedResponse::resourcesIsSet() const
{
    return m_ResourcesIsSet;
}

void GetUnsubscribersPaginatedResponse::unsetResources()
{
    m_ResourcesIsSet = false;
}

}
}
}
}


