/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/InviteSubaccount_request.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

InviteSubaccount_request::InviteSubaccount_request()
{
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_RoleIsSet = false;
}

InviteSubaccount_request::~InviteSubaccount_request()
{
}

void InviteSubaccount_request::validate()
{
    // TODO: implement validation
}

web::json::value InviteSubaccount_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_RoleIsSet)
    {   
        
        utility::string_t refVal = fromRoleEnum(m_Role);
        val[utility::conversions::to_string_t(_XPLATSTR("role"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool InviteSubaccount_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("role")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRole;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRole);
            
            setRole(toRoleEnum(refVal_setRole));
            
        }
    }
    return ok;
}

void InviteSubaccount_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_RoleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("role")), fromRoleEnum(m_Role)));
    }
}

bool InviteSubaccount_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        utility::string_t refVal_setRole;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("role"))), refVal_setRole );
        setRole(toRoleEnum(refVal_setRole));
    }
    return ok;
}

InviteSubaccount_request::RoleEnum InviteSubaccount_request::toRoleEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("A")) {
        return RoleEnum::A;
    }
    
    if (value == utility::conversions::to_string_t("U")) {
        return RoleEnum::U;
    }
    
    throw std::invalid_argument("Invalid value for conversion to RoleEnum");
}


const utility::string_t InviteSubaccount_request::fromRoleEnum(const RoleEnum value) const
{
    switch(value)
    {
        
        case RoleEnum::A: return utility::conversions::to_string_t("A");
        
        case RoleEnum::U: return utility::conversions::to_string_t("U");
        
    }
}


utility::string_t InviteSubaccount_request::getEmail() const
{
    return m_Email;
}


void InviteSubaccount_request::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool InviteSubaccount_request::emailIsSet() const
{
    return m_EmailIsSet;
}

void InviteSubaccount_request::unsetEmail()
{
    m_EmailIsSet = false;
}
InviteSubaccount_request::RoleEnum InviteSubaccount_request::getRole() const
{
    return m_Role;
}


void InviteSubaccount_request::setRole(const RoleEnum value)
{
    m_Role = value;
    m_RoleIsSet = true;
}

bool InviteSubaccount_request::roleIsSet() const
{
    return m_RoleIsSet;
}

void InviteSubaccount_request::unsetRole()
{
    m_RoleIsSet = false;
}

}
}
}
}


