/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/List.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

List::List()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Favorited = false;
    m_FavoritedIsSet = false;
    m_MembersCount = 0;
    m_MembersCountIsSet = false;
    m_UserIsSet = false;
    m_Service = false;
    m_ServiceIsSet = false;
    m_Shared = false;
    m_SharedIsSet = false;
    m_AvatarIsSet = false;
    m_IsDefault = false;
    m_IsDefaultIsSet = false;
}

List::~List()
{
}

void List::validate()
{
    // TODO: implement validation
}

web::json::value List::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_FavoritedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("favorited"))] = ModelBase::toJson(m_Favorited);
    }
    if(m_MembersCountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("membersCount"))] = ModelBase::toJson(m_MembersCount);
    }
    if(m_UserIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("user"))] = ModelBase::toJson(m_User);
    }
    if(m_ServiceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("service"))] = ModelBase::toJson(m_Service);
    }
    if(m_SharedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("shared"))] = ModelBase::toJson(m_Shared);
    }
    if(m_AvatarIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar"))] = ModelBase::toJson(m_Avatar);
    }
    if(m_IsDefaultIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("isDefault"))] = ModelBase::toJson(m_IsDefault);
    }

    return val;
}

bool List::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("favorited")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFavorited;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFavorited);
            setFavorited(refVal_setFavorited);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("membersCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("membersCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMembersCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMembersCount);
            setMembersCount(refVal_setMembersCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<User> refVal_setUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUser);
            setUser(refVal_setUser);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("service"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("service")));
        if(!fieldValue.is_null())
        {
            bool refVal_setService;
            ok &= ModelBase::fromJson(fieldValue, refVal_setService);
            setService(refVal_setService);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shared"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shared")));
        if(!fieldValue.is_null())
        {
            bool refVal_setShared;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShared);
            setShared(refVal_setShared);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ListImage> refVal_setAvatar;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatar);
            setAvatar(refVal_setAvatar);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isDefault"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isDefault")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsDefault;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsDefault);
            setIsDefault(refVal_setIsDefault);
            
        }
    }
    return ok;
}

void List::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_FavoritedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("favorited")), m_Favorited));
    }
    if(m_MembersCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("membersCount")), m_MembersCount));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user")), m_User));
    }
    if(m_ServiceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("service")), m_Service));
    }
    if(m_SharedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shared")), m_Shared));
    }
    if(m_AvatarIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar")), m_Avatar));
    }
    if(m_IsDefaultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isDefault")), m_IsDefault));
    }
}

bool List::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        bool refVal_setFavorited;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))), refVal_setFavorited );
        setFavorited(refVal_setFavorited);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("membersCount"))))
    {
        int32_t refVal_setMembersCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("membersCount"))), refVal_setMembersCount );
        setMembersCount(refVal_setMembersCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        std::shared_ptr<User> refVal_setUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user"))), refVal_setUser );
        setUser(refVal_setUser);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("service"))))
    {
        bool refVal_setService;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("service"))), refVal_setService );
        setService(refVal_setService);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shared"))))
    {
        bool refVal_setShared;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shared"))), refVal_setShared );
        setShared(refVal_setShared);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        std::shared_ptr<ListImage> refVal_setAvatar;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))), refVal_setAvatar );
        setAvatar(refVal_setAvatar);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isDefault"))))
    {
        bool refVal_setIsDefault;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isDefault"))), refVal_setIsDefault );
        setIsDefault(refVal_setIsDefault);
    }
    return ok;
}


int32_t List::getId() const
{
    return m_Id;
}

void List::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool List::idIsSet() const
{
    return m_IdIsSet;
}

void List::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t List::getName() const
{
    return m_Name;
}


void List::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool List::nameIsSet() const
{
    return m_NameIsSet;
}

void List::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t List::getDescription() const
{
    return m_Description;
}


void List::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool List::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void List::unsetDescription()
{
    m_DescriptionIsSet = false;
}
bool List::isFavorited() const
{
    return m_Favorited;
}

void List::setFavorited(bool value)
{
    m_Favorited = value;
    m_FavoritedIsSet = true;
}

bool List::favoritedIsSet() const
{
    return m_FavoritedIsSet;
}

void List::unsetFavorited()
{
    m_FavoritedIsSet = false;
}
int32_t List::getMembersCount() const
{
    return m_MembersCount;
}

void List::setMembersCount(int32_t value)
{
    m_MembersCount = value;
    m_MembersCountIsSet = true;
}

bool List::membersCountIsSet() const
{
    return m_MembersCountIsSet;
}

void List::unsetMembersCount()
{
    m_MembersCountIsSet = false;
}
std::shared_ptr<User> List::getUser() const
{
    return m_User;
}


void List::setUser(const std::shared_ptr<User>& value)
{
    m_User = value;
    m_UserIsSet = true;
}

bool List::userIsSet() const
{
    return m_UserIsSet;
}

void List::unsetUser()
{
    m_UserIsSet = false;
}
bool List::isService() const
{
    return m_Service;
}

void List::setService(bool value)
{
    m_Service = value;
    m_ServiceIsSet = true;
}

bool List::serviceIsSet() const
{
    return m_ServiceIsSet;
}

void List::unsetService()
{
    m_ServiceIsSet = false;
}
bool List::isShared() const
{
    return m_Shared;
}

void List::setShared(bool value)
{
    m_Shared = value;
    m_SharedIsSet = true;
}

bool List::sharedIsSet() const
{
    return m_SharedIsSet;
}

void List::unsetShared()
{
    m_SharedIsSet = false;
}
std::shared_ptr<ListImage> List::getAvatar() const
{
    return m_Avatar;
}


void List::setAvatar(const std::shared_ptr<ListImage>& value)
{
    m_Avatar = value;
    m_AvatarIsSet = true;
}

bool List::avatarIsSet() const
{
    return m_AvatarIsSet;
}

void List::unsetAvatar()
{
    m_AvatarIsSet = false;
}
bool List::isIsDefault() const
{
    return m_IsDefault;
}

void List::setIsDefault(bool value)
{
    m_IsDefault = value;
    m_IsDefaultIsSet = true;
}

bool List::isDefaultIsSet() const
{
    return m_IsDefaultIsSet;
}

void List::unsetIsDefault()
{
    m_IsDefaultIsSet = false;
}

}
}
}
}


