/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/MessagesIcs.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

MessagesIcs::MessagesIcs()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_NextSend = utility::datetime();
    m_NextSendIsSet = false;
    m_Rrule = utility::conversions::to_string_t("");
    m_RruleIsSet = false;
    m_SessionIsSet = false;
    m_LastSent = utility::datetime();
    m_LastSentIsSet = false;
    m_ContactName = utility::conversions::to_string_t("");
    m_ContactNameIsSet = false;
    m_ParametersIsSet = false;
    m_TypeIsSet = false;
    m_Summary = utility::conversions::to_string_t("");
    m_SummaryIsSet = false;
    m_TextParametersIsSet = false;
    m_FirstOccurrence = utility::datetime();
    m_FirstOccurrenceIsSet = false;
    m_LastOccurrence = utility::datetime();
    m_LastOccurrenceIsSet = false;
    m_RecipientsCount = 0;
    m_RecipientsCountIsSet = false;
    m_Timezone = utility::conversions::to_string_t("");
    m_TimezoneIsSet = false;
    m_Completed = false;
    m_CompletedIsSet = false;
    m_Avatar = utility::conversions::to_string_t("");
    m_AvatarIsSet = false;
    m_CreatedAt = utility::datetime();
    m_CreatedAtIsSet = false;
}

MessagesIcs::~MessagesIcs()
{
}

void MessagesIcs::validate()
{
    // TODO: implement validation
}

web::json::value MessagesIcs::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NextSendIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("nextSend"))] = ModelBase::toJson(m_NextSend);
    }
    if(m_RruleIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("rrule"))] = ModelBase::toJson(m_Rrule);
    }
    if(m_SessionIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("session"))] = ModelBase::toJson(m_Session);
    }
    if(m_LastSentIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastSent"))] = ModelBase::toJson(m_LastSent);
    }
    if(m_ContactNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("contactName"))] = ModelBase::toJson(m_ContactName);
    }
    if(m_ParametersIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("parameters"))] = ModelBase::toJson(m_Parameters);
    }
    if(m_TypeIsSet)
    {   
        
        utility::string_t refVal = fromTypeEnum(m_Type);
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(refVal);
        
    }
    if(m_SummaryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("summary"))] = ModelBase::toJson(m_Summary);
    }
    if(m_TextParametersIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("textParameters"))] = ModelBase::toJson(m_TextParameters);
    }
    if(m_FirstOccurrenceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("firstOccurrence"))] = ModelBase::toJson(m_FirstOccurrence);
    }
    if(m_LastOccurrenceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastOccurrence"))] = ModelBase::toJson(m_LastOccurrence);
    }
    if(m_RecipientsCountIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("recipientsCount"))] = ModelBase::toJson(m_RecipientsCount);
    }
    if(m_TimezoneIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("timezone"))] = ModelBase::toJson(m_Timezone);
    }
    if(m_CompletedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("completed"))] = ModelBase::toJson(m_Completed);
    }
    if(m_AvatarIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("avatar"))] = ModelBase::toJson(m_Avatar);
    }
    if(m_CreatedAtIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("createdAt"))] = ModelBase::toJson(m_CreatedAt);
    }

    return val;
}

bool MessagesIcs::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("nextSend"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("nextSend")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setNextSend;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNextSend);
            setNextSend(refVal_setNextSend);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("rrule"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("rrule")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRrule;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRrule);
            setRrule(refVal_setRrule);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("session"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("session")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<MessageSession> refVal_setSession;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSession);
            setSession(refVal_setSession);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastSent"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastSent")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastSent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastSent);
            setLastSent(refVal_setLastSent);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("contactName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("contactName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContactName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContactName);
            setContactName(refVal_setContactName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("parameters"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("parameters")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<MessagesIcs_parameters> refVal_setParameters;
            ok &= ModelBase::fromJson(fieldValue, refVal_setParameters);
            setParameters(refVal_setParameters);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            
            setType(toTypeEnum(refVal_setType));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("summary")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSummary;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSummary);
            setSummary(refVal_setSummary);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("textParameters"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("textParameters")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<MessagesIcs_textParameters> refVal_setTextParameters;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTextParameters);
            setTextParameters(refVal_setTextParameters);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("firstOccurrence"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("firstOccurrence")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setFirstOccurrence;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFirstOccurrence);
            setFirstOccurrence(refVal_setFirstOccurrence);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastOccurrence"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastOccurrence")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastOccurrence;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastOccurrence);
            setLastOccurrence(refVal_setLastOccurrence);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("recipientsCount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("recipientsCount")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setRecipientsCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRecipientsCount);
            setRecipientsCount(refVal_setRecipientsCount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timezone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTimezone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimezone);
            setTimezone(refVal_setTimezone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("completed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("completed")));
        if(!fieldValue.is_null())
        {
            bool refVal_setCompleted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompleted);
            setCompleted(refVal_setCompleted);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("avatar")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatar;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatar);
            setAvatar(refVal_setAvatar);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("createdAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    return ok;
}

void MessagesIcs::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NextSendIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("nextSend")), m_NextSend));
    }
    if(m_RruleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("rrule")), m_Rrule));
    }
    if(m_SessionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("session")), m_Session));
    }
    if(m_LastSentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastSent")), m_LastSent));
    }
    if(m_ContactNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("contactName")), m_ContactName));
    }
    if(m_ParametersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("parameters")), m_Parameters));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), fromTypeEnum(m_Type)));
    }
    if(m_SummaryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("summary")), m_Summary));
    }
    if(m_TextParametersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("textParameters")), m_TextParameters));
    }
    if(m_FirstOccurrenceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("firstOccurrence")), m_FirstOccurrence));
    }
    if(m_LastOccurrenceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastOccurrence")), m_LastOccurrence));
    }
    if(m_RecipientsCountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("recipientsCount")), m_RecipientsCount));
    }
    if(m_TimezoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timezone")), m_Timezone));
    }
    if(m_CompletedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("completed")), m_Completed));
    }
    if(m_AvatarIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("avatar")), m_Avatar));
    }
    if(m_CreatedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("createdAt")), m_CreatedAt));
    }
}

bool MessagesIcs::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("nextSend"))))
    {
        utility::datetime refVal_setNextSend;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("nextSend"))), refVal_setNextSend );
        setNextSend(refVal_setNextSend);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("rrule"))))
    {
        utility::string_t refVal_setRrule;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("rrule"))), refVal_setRrule );
        setRrule(refVal_setRrule);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("session"))))
    {
        std::shared_ptr<MessageSession> refVal_setSession;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("session"))), refVal_setSession );
        setSession(refVal_setSession);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastSent"))))
    {
        utility::datetime refVal_setLastSent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastSent"))), refVal_setLastSent );
        setLastSent(refVal_setLastSent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("contactName"))))
    {
        utility::string_t refVal_setContactName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("contactName"))), refVal_setContactName );
        setContactName(refVal_setContactName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("parameters"))))
    {
        std::shared_ptr<MessagesIcs_parameters> refVal_setParameters;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("parameters"))), refVal_setParameters );
        setParameters(refVal_setParameters);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(toTypeEnum(refVal_setType));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("summary"))))
    {
        utility::string_t refVal_setSummary;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("summary"))), refVal_setSummary );
        setSummary(refVal_setSummary);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("textParameters"))))
    {
        std::shared_ptr<MessagesIcs_textParameters> refVal_setTextParameters;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("textParameters"))), refVal_setTextParameters );
        setTextParameters(refVal_setTextParameters);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("firstOccurrence"))))
    {
        utility::datetime refVal_setFirstOccurrence;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("firstOccurrence"))), refVal_setFirstOccurrence );
        setFirstOccurrence(refVal_setFirstOccurrence);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastOccurrence"))))
    {
        utility::datetime refVal_setLastOccurrence;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastOccurrence"))), refVal_setLastOccurrence );
        setLastOccurrence(refVal_setLastOccurrence);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("recipientsCount"))))
    {
        int32_t refVal_setRecipientsCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("recipientsCount"))), refVal_setRecipientsCount );
        setRecipientsCount(refVal_setRecipientsCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        utility::string_t refVal_setTimezone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))), refVal_setTimezone );
        setTimezone(refVal_setTimezone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("completed"))))
    {
        bool refVal_setCompleted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("completed"))), refVal_setCompleted );
        setCompleted(refVal_setCompleted);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))))
    {
        utility::string_t refVal_setAvatar;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("avatar"))), refVal_setAvatar );
        setAvatar(refVal_setAvatar);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("createdAt"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    return ok;
}

MessagesIcs::TypeEnum MessagesIcs::toTypeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("Once")) {
        return TypeEnum::ONCE;
    }
    
    if (value == utility::conversions::to_string_t("Hourly")) {
        return TypeEnum::HOURLY;
    }
    
    if (value == utility::conversions::to_string_t("Daily")) {
        return TypeEnum::DAILY;
    }
    
    if (value == utility::conversions::to_string_t("Weekly")) {
        return TypeEnum::WEEKLY;
    }
    
    if (value == utility::conversions::to_string_t("Monthly")) {
        return TypeEnum::MONTHLY;
    }
    
    if (value == utility::conversions::to_string_t("Yearly")) {
        return TypeEnum::YEARLY;
    }
    
    throw std::invalid_argument("Invalid value for conversion to TypeEnum");
}


const utility::string_t MessagesIcs::fromTypeEnum(const TypeEnum value) const
{
    switch(value)
    {
        
        case TypeEnum::ONCE: return utility::conversions::to_string_t("Once");
        
        case TypeEnum::HOURLY: return utility::conversions::to_string_t("Hourly");
        
        case TypeEnum::DAILY: return utility::conversions::to_string_t("Daily");
        
        case TypeEnum::WEEKLY: return utility::conversions::to_string_t("Weekly");
        
        case TypeEnum::MONTHLY: return utility::conversions::to_string_t("Monthly");
        
        case TypeEnum::YEARLY: return utility::conversions::to_string_t("Yearly");
        
    }
}


int32_t MessagesIcs::getId() const
{
    return m_Id;
}

void MessagesIcs::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool MessagesIcs::idIsSet() const
{
    return m_IdIsSet;
}

void MessagesIcs::unsetId()
{
    m_IdIsSet = false;
}
utility::datetime MessagesIcs::getNextSend() const
{
    return m_NextSend;
}


void MessagesIcs::setNextSend(const utility::datetime& value)
{
    m_NextSend = value;
    m_NextSendIsSet = true;
}

bool MessagesIcs::nextSendIsSet() const
{
    return m_NextSendIsSet;
}

void MessagesIcs::unsetNextSend()
{
    m_NextSendIsSet = false;
}
utility::string_t MessagesIcs::getRrule() const
{
    return m_Rrule;
}


void MessagesIcs::setRrule(const utility::string_t& value)
{
    m_Rrule = value;
    m_RruleIsSet = true;
}

bool MessagesIcs::rruleIsSet() const
{
    return m_RruleIsSet;
}

void MessagesIcs::unsetRrule()
{
    m_RruleIsSet = false;
}
std::shared_ptr<MessageSession> MessagesIcs::getSession() const
{
    return m_Session;
}


void MessagesIcs::setSession(const std::shared_ptr<MessageSession>& value)
{
    m_Session = value;
    m_SessionIsSet = true;
}

bool MessagesIcs::sessionIsSet() const
{
    return m_SessionIsSet;
}

void MessagesIcs::unsetSession()
{
    m_SessionIsSet = false;
}
utility::datetime MessagesIcs::getLastSent() const
{
    return m_LastSent;
}


void MessagesIcs::setLastSent(const utility::datetime& value)
{
    m_LastSent = value;
    m_LastSentIsSet = true;
}

bool MessagesIcs::lastSentIsSet() const
{
    return m_LastSentIsSet;
}

void MessagesIcs::unsetLastSent()
{
    m_LastSentIsSet = false;
}
utility::string_t MessagesIcs::getContactName() const
{
    return m_ContactName;
}


void MessagesIcs::setContactName(const utility::string_t& value)
{
    m_ContactName = value;
    m_ContactNameIsSet = true;
}

bool MessagesIcs::contactNameIsSet() const
{
    return m_ContactNameIsSet;
}

void MessagesIcs::unsetContactName()
{
    m_ContactNameIsSet = false;
}
std::shared_ptr<MessagesIcs_parameters> MessagesIcs::getParameters() const
{
    return m_Parameters;
}


void MessagesIcs::setParameters(const std::shared_ptr<MessagesIcs_parameters>& value)
{
    m_Parameters = value;
    m_ParametersIsSet = true;
}

bool MessagesIcs::parametersIsSet() const
{
    return m_ParametersIsSet;
}

void MessagesIcs::unsetParameters()
{
    m_ParametersIsSet = false;
}
MessagesIcs::TypeEnum MessagesIcs::getType() const
{
    return m_Type;
}


void MessagesIcs::setType(const TypeEnum value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool MessagesIcs::typeIsSet() const
{
    return m_TypeIsSet;
}

void MessagesIcs::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t MessagesIcs::getSummary() const
{
    return m_Summary;
}


void MessagesIcs::setSummary(const utility::string_t& value)
{
    m_Summary = value;
    m_SummaryIsSet = true;
}

bool MessagesIcs::summaryIsSet() const
{
    return m_SummaryIsSet;
}

void MessagesIcs::unsetSummary()
{
    m_SummaryIsSet = false;
}
std::shared_ptr<MessagesIcs_textParameters> MessagesIcs::getTextParameters() const
{
    return m_TextParameters;
}


void MessagesIcs::setTextParameters(const std::shared_ptr<MessagesIcs_textParameters>& value)
{
    m_TextParameters = value;
    m_TextParametersIsSet = true;
}

bool MessagesIcs::textParametersIsSet() const
{
    return m_TextParametersIsSet;
}

void MessagesIcs::unsetTextParameters()
{
    m_TextParametersIsSet = false;
}
utility::datetime MessagesIcs::getFirstOccurrence() const
{
    return m_FirstOccurrence;
}


void MessagesIcs::setFirstOccurrence(const utility::datetime& value)
{
    m_FirstOccurrence = value;
    m_FirstOccurrenceIsSet = true;
}

bool MessagesIcs::firstOccurrenceIsSet() const
{
    return m_FirstOccurrenceIsSet;
}

void MessagesIcs::unsetFirstOccurrence()
{
    m_FirstOccurrenceIsSet = false;
}
utility::datetime MessagesIcs::getLastOccurrence() const
{
    return m_LastOccurrence;
}


void MessagesIcs::setLastOccurrence(const utility::datetime& value)
{
    m_LastOccurrence = value;
    m_LastOccurrenceIsSet = true;
}

bool MessagesIcs::lastOccurrenceIsSet() const
{
    return m_LastOccurrenceIsSet;
}

void MessagesIcs::unsetLastOccurrence()
{
    m_LastOccurrenceIsSet = false;
}
int32_t MessagesIcs::getRecipientsCount() const
{
    return m_RecipientsCount;
}

void MessagesIcs::setRecipientsCount(int32_t value)
{
    m_RecipientsCount = value;
    m_RecipientsCountIsSet = true;
}

bool MessagesIcs::recipientsCountIsSet() const
{
    return m_RecipientsCountIsSet;
}

void MessagesIcs::unsetRecipientsCount()
{
    m_RecipientsCountIsSet = false;
}
utility::string_t MessagesIcs::getTimezone() const
{
    return m_Timezone;
}


void MessagesIcs::setTimezone(const utility::string_t& value)
{
    m_Timezone = value;
    m_TimezoneIsSet = true;
}

bool MessagesIcs::timezoneIsSet() const
{
    return m_TimezoneIsSet;
}

void MessagesIcs::unsetTimezone()
{
    m_TimezoneIsSet = false;
}
bool MessagesIcs::isCompleted() const
{
    return m_Completed;
}

void MessagesIcs::setCompleted(bool value)
{
    m_Completed = value;
    m_CompletedIsSet = true;
}

bool MessagesIcs::completedIsSet() const
{
    return m_CompletedIsSet;
}

void MessagesIcs::unsetCompleted()
{
    m_CompletedIsSet = false;
}
utility::string_t MessagesIcs::getAvatar() const
{
    return m_Avatar;
}


void MessagesIcs::setAvatar(const utility::string_t& value)
{
    m_Avatar = value;
    m_AvatarIsSet = true;
}

bool MessagesIcs::avatarIsSet() const
{
    return m_AvatarIsSet;
}

void MessagesIcs::unsetAvatar()
{
    m_AvatarIsSet = false;
}
utility::datetime MessagesIcs::getCreatedAt() const
{
    return m_CreatedAt;
}


void MessagesIcs::setCreatedAt(const utility::datetime& value)
{
    m_CreatedAt = value;
    m_CreatedAtIsSet = true;
}

bool MessagesIcs::createdAtIsSet() const
{
    return m_CreatedAtIsSet;
}

void MessagesIcs::unsetCreatedAt()
{
    m_CreatedAtIsSet = false;
}

}
}
}
}


