/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/MessageTemplate.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

MessageTemplate::MessageTemplate()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Content = utility::conversions::to_string_t("");
    m_ContentIsSet = false;
    m_LastModified = utility::datetime();
    m_LastModifiedIsSet = false;
}

MessageTemplate::~MessageTemplate()
{
}

void MessageTemplate::validate()
{
    // TODO: implement validation
}

web::json::value MessageTemplate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_ContentIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("content"))] = ModelBase::toJson(m_Content);
    }
    if(m_LastModifiedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastModified"))] = ModelBase::toJson(m_LastModified);
    }

    return val;
}

bool MessageTemplate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("content")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContent);
            setContent(refVal_setContent);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastModified"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastModified")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastModified;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastModified);
            setLastModified(refVal_setLastModified);
            
        }
    }
    return ok;
}

void MessageTemplate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_ContentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("content")), m_Content));
    }
    if(m_LastModifiedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastModified")), m_LastModified));
    }
}

bool MessageTemplate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        utility::string_t refVal_setContent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("content"))), refVal_setContent );
        setContent(refVal_setContent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastModified"))))
    {
        utility::datetime refVal_setLastModified;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastModified"))), refVal_setLastModified );
        setLastModified(refVal_setLastModified);
    }
    return ok;
}


int32_t MessageTemplate::getId() const
{
    return m_Id;
}

void MessageTemplate::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool MessageTemplate::idIsSet() const
{
    return m_IdIsSet;
}

void MessageTemplate::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t MessageTemplate::getName() const
{
    return m_Name;
}


void MessageTemplate::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool MessageTemplate::nameIsSet() const
{
    return m_NameIsSet;
}

void MessageTemplate::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t MessageTemplate::getContent() const
{
    return m_Content;
}


void MessageTemplate::setContent(const utility::string_t& value)
{
    m_Content = value;
    m_ContentIsSet = true;
}

bool MessageTemplate::contentIsSet() const
{
    return m_ContentIsSet;
}

void MessageTemplate::unsetContent()
{
    m_ContentIsSet = false;
}
utility::datetime MessageTemplate::getLastModified() const
{
    return m_LastModified;
}


void MessageTemplate::setLastModified(const utility::datetime& value)
{
    m_LastModified = value;
    m_LastModifiedIsSet = true;
}

bool MessageTemplate::lastModifiedIsSet() const
{
    return m_LastModifiedIsSet;
}

void MessageTemplate::unsetLastModified()
{
    m_LastModifiedIsSet = false;
}

}
}
}
}


