/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/SenderId.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

SenderId::SenderId()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_DisplayTimeFormat = utility::conversions::to_string_t("");
    m_DisplayTimeFormatIsSet = false;
    m_SenderId = utility::conversions::to_string_t("");
    m_SenderIdIsSet = false;
    m_UserIsSet = false;
    m_StatusIsSet = false;
}

SenderId::~SenderId()
{
}

void SenderId::validate()
{
    // TODO: implement validation
}

web::json::value SenderId::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_DisplayTimeFormatIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat"))] = ModelBase::toJson(m_DisplayTimeFormat);
    }
    if(m_SenderIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("senderId"))] = ModelBase::toJson(m_SenderId);
    }
    if(m_UserIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("user"))] = ModelBase::toJson(m_User);
    }
    if(m_StatusIsSet)
    {   
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool SenderId::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDisplayTimeFormat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDisplayTimeFormat);
            setDisplayTimeFormat(refVal_setDisplayTimeFormat);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("senderId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("senderId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSenderId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSenderId);
            setSenderId(refVal_setSenderId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<User> refVal_setUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUser);
            setUser(refVal_setUser);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    return ok;
}

void SenderId::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_DisplayTimeFormatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat")), m_DisplayTimeFormat));
    }
    if(m_SenderIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("senderId")), m_SenderId));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user")), m_User));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
}

bool SenderId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat"))))
    {
        utility::string_t refVal_setDisplayTimeFormat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("displayTimeFormat"))), refVal_setDisplayTimeFormat );
        setDisplayTimeFormat(refVal_setDisplayTimeFormat);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("senderId"))))
    {
        utility::string_t refVal_setSenderId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("senderId"))), refVal_setSenderId );
        setSenderId(refVal_setSenderId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        std::shared_ptr<User> refVal_setUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user"))), refVal_setUser );
        setUser(refVal_setUser);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    return ok;
}

SenderId::StatusEnum SenderId::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("A")) {
        return StatusEnum::A;
    }
    
    if (value == utility::conversions::to_string_t("R")) {
        return StatusEnum::R;
    }
    
    if (value == utility::conversions::to_string_t("P")) {
        return StatusEnum::P;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t SenderId::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::A: return utility::conversions::to_string_t("A");
        
        case StatusEnum::R: return utility::conversions::to_string_t("R");
        
        case StatusEnum::P: return utility::conversions::to_string_t("P");
        
    }
}


int32_t SenderId::getId() const
{
    return m_Id;
}

void SenderId::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SenderId::idIsSet() const
{
    return m_IdIsSet;
}

void SenderId::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SenderId::getDisplayTimeFormat() const
{
    return m_DisplayTimeFormat;
}


void SenderId::setDisplayTimeFormat(const utility::string_t& value)
{
    m_DisplayTimeFormat = value;
    m_DisplayTimeFormatIsSet = true;
}

bool SenderId::displayTimeFormatIsSet() const
{
    return m_DisplayTimeFormatIsSet;
}

void SenderId::unsetDisplayTimeFormat()
{
    m_DisplayTimeFormatIsSet = false;
}
utility::string_t SenderId::getSenderId() const
{
    return m_SenderId;
}


void SenderId::setSenderId(const utility::string_t& value)
{
    m_SenderId = value;
    m_SenderIdIsSet = true;
}

bool SenderId::senderIdIsSet() const
{
    return m_SenderIdIsSet;
}

void SenderId::unsetSenderId()
{
    m_SenderIdIsSet = false;
}
std::shared_ptr<User> SenderId::getUser() const
{
    return m_User;
}


void SenderId::setUser(const std::shared_ptr<User>& value)
{
    m_User = value;
    m_UserIsSet = true;
}

bool SenderId::userIsSet() const
{
    return m_UserIsSet;
}

void SenderId::unsetUser()
{
    m_UserIsSet = false;
}
SenderId::StatusEnum SenderId::getStatus() const
{
    return m_Status;
}


void SenderId::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool SenderId::statusIsSet() const
{
    return m_StatusIsSet;
}

void SenderId::unsetStatus()
{
    m_StatusIsSet = false;
}

}
}
}
}


