/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/SenderSettingsItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

SenderSettingsItem::SenderSettingsItem()
{
    m_Country = utility::conversions::to_string_t("");
    m_CountryIsSet = false;
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
}

SenderSettingsItem::~SenderSettingsItem()
{
}

void SenderSettingsItem::validate()
{
    // TODO: implement validation
}

web::json::value SenderSettingsItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CountryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country);
    }
    if(m_PhoneIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }

    return val;
}

bool SenderSettingsItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    return ok;
}

void SenderSettingsItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CountryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
}

bool SenderSettingsItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    return ok;
}


utility::string_t SenderSettingsItem::getCountry() const
{
    return m_Country;
}


void SenderSettingsItem::setCountry(const utility::string_t& value)
{
    m_Country = value;
    m_CountryIsSet = true;
}

bool SenderSettingsItem::countryIsSet() const
{
    return m_CountryIsSet;
}

void SenderSettingsItem::unsetCountry()
{
    m_CountryIsSet = false;
}
utility::string_t SenderSettingsItem::getPhone() const
{
    return m_Phone;
}


void SenderSettingsItem::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool SenderSettingsItem::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void SenderSettingsItem::unsetPhone()
{
    m_PhoneIsSet = false;
}

}
}
}
}


