/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/Timezone.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

Timezone::Timezone()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Area = utility::conversions::to_string_t("");
    m_AreaIsSet = false;
    m_Dst = 0;
    m_DstIsSet = false;
    m_Offset = 0;
    m_OffsetIsSet = false;
    m_Timezone = utility::conversions::to_string_t("");
    m_TimezoneIsSet = false;
}

Timezone::~Timezone()
{
}

void Timezone::validate()
{
    // TODO: implement validation
}

web::json::value Timezone::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_AreaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("area"))] = ModelBase::toJson(m_Area);
    }
    if(m_DstIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("dst"))] = ModelBase::toJson(m_Dst);
    }
    if(m_OffsetIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("offset"))] = ModelBase::toJson(m_Offset);
    }
    if(m_TimezoneIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("timezone"))] = ModelBase::toJson(m_Timezone);
    }

    return val;
}

bool Timezone::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("area"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("area")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setArea;
            ok &= ModelBase::fromJson(fieldValue, refVal_setArea);
            setArea(refVal_setArea);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("dst"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("dst")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDst;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDst);
            setDst(refVal_setDst);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("offset"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("offset")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOffset;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOffset);
            setOffset(refVal_setOffset);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("timezone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTimezone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTimezone);
            setTimezone(refVal_setTimezone);
            
        }
    }
    return ok;
}

void Timezone::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_AreaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("area")), m_Area));
    }
    if(m_DstIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("dst")), m_Dst));
    }
    if(m_OffsetIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("offset")), m_Offset));
    }
    if(m_TimezoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("timezone")), m_Timezone));
    }
}

bool Timezone::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("area"))))
    {
        utility::string_t refVal_setArea;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("area"))), refVal_setArea );
        setArea(refVal_setArea);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("dst"))))
    {
        int32_t refVal_setDst;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("dst"))), refVal_setDst );
        setDst(refVal_setDst);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("offset"))))
    {
        int32_t refVal_setOffset;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("offset"))), refVal_setOffset );
        setOffset(refVal_setOffset);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))))
    {
        utility::string_t refVal_setTimezone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("timezone"))), refVal_setTimezone );
        setTimezone(refVal_setTimezone);
    }
    return ok;
}


int32_t Timezone::getId() const
{
    return m_Id;
}

void Timezone::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Timezone::idIsSet() const
{
    return m_IdIsSet;
}

void Timezone::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Timezone::getArea() const
{
    return m_Area;
}


void Timezone::setArea(const utility::string_t& value)
{
    m_Area = value;
    m_AreaIsSet = true;
}

bool Timezone::areaIsSet() const
{
    return m_AreaIsSet;
}

void Timezone::unsetArea()
{
    m_AreaIsSet = false;
}
int32_t Timezone::getDst() const
{
    return m_Dst;
}

void Timezone::setDst(int32_t value)
{
    m_Dst = value;
    m_DstIsSet = true;
}

bool Timezone::dstIsSet() const
{
    return m_DstIsSet;
}

void Timezone::unsetDst()
{
    m_DstIsSet = false;
}
int32_t Timezone::getOffset() const
{
    return m_Offset;
}

void Timezone::setOffset(int32_t value)
{
    m_Offset = value;
    m_OffsetIsSet = true;
}

bool Timezone::offsetIsSet() const
{
    return m_OffsetIsSet;
}

void Timezone::unsetOffset()
{
    m_OffsetIsSet = false;
}
utility::string_t Timezone::getTimezone() const
{
    return m_Timezone;
}


void Timezone::setTimezone(const utility::string_t& value)
{
    m_Timezone = value;
    m_TimezoneIsSet = true;
}

bool Timezone::timezoneIsSet() const
{
    return m_TimezoneIsSet;
}

void Timezone::unsetTimezone()
{
    m_TimezoneIsSet = false;
}

}
}
}
}


