/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/UpdateList_request.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

UpdateList_request::UpdateList_request()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Shared = false;
    m_SharedIsSet = false;
    m_Favorited = false;
    m_FavoritedIsSet = false;
    m_IsDefault = false;
    m_IsDefaultIsSet = false;
}

UpdateList_request::~UpdateList_request()
{
}

void UpdateList_request::validate()
{
    // TODO: implement validation
}

web::json::value UpdateList_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_NameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_SharedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("shared"))] = ModelBase::toJson(m_Shared);
    }
    if(m_FavoritedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("favorited"))] = ModelBase::toJson(m_Favorited);
    }
    if(m_IsDefaultIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("isDefault"))] = ModelBase::toJson(m_IsDefault);
    }

    return val;
}

bool UpdateList_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shared"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shared")));
        if(!fieldValue.is_null())
        {
            bool refVal_setShared;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShared);
            setShared(refVal_setShared);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("favorited")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFavorited;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFavorited);
            setFavorited(refVal_setFavorited);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isDefault"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isDefault")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsDefault;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsDefault);
            setIsDefault(refVal_setIsDefault);
            
        }
    }
    return ok;
}

void UpdateList_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_SharedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shared")), m_Shared));
    }
    if(m_FavoritedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("favorited")), m_Favorited));
    }
    if(m_IsDefaultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isDefault")), m_IsDefault));
    }
}

bool UpdateList_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shared"))))
    {
        bool refVal_setShared;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shared"))), refVal_setShared );
        setShared(refVal_setShared);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        bool refVal_setFavorited;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))), refVal_setFavorited );
        setFavorited(refVal_setFavorited);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isDefault"))))
    {
        bool refVal_setIsDefault;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isDefault"))), refVal_setIsDefault );
        setIsDefault(refVal_setIsDefault);
    }
    return ok;
}


utility::string_t UpdateList_request::getName() const
{
    return m_Name;
}


void UpdateList_request::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool UpdateList_request::nameIsSet() const
{
    return m_NameIsSet;
}

void UpdateList_request::unsetName()
{
    m_NameIsSet = false;
}
bool UpdateList_request::isShared() const
{
    return m_Shared;
}

void UpdateList_request::setShared(bool value)
{
    m_Shared = value;
    m_SharedIsSet = true;
}

bool UpdateList_request::sharedIsSet() const
{
    return m_SharedIsSet;
}

void UpdateList_request::unsetShared()
{
    m_SharedIsSet = false;
}
bool UpdateList_request::isFavorited() const
{
    return m_Favorited;
}

void UpdateList_request::setFavorited(bool value)
{
    m_Favorited = value;
    m_FavoritedIsSet = true;
}

bool UpdateList_request::favoritedIsSet() const
{
    return m_FavoritedIsSet;
}

void UpdateList_request::unsetFavorited()
{
    m_FavoritedIsSet = false;
}
bool UpdateList_request::isIsDefault() const
{
    return m_IsDefault;
}

void UpdateList_request::setIsDefault(bool value)
{
    m_IsDefault = value;
    m_IsDefaultIsSet = true;
}

bool UpdateList_request::isDefaultIsSet() const
{
    return m_IsDefaultIsSet;
}

void UpdateList_request::unsetIsDefault()
{
    m_IsDefaultIsSet = false;
}

}
}
}
}


