/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/UpdateContact_request.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

UpdateContact_request::UpdateContact_request()
{
    m_FirstName = utility::conversions::to_string_t("");
    m_FirstNameIsSet = false;
    m_LastName = utility::conversions::to_string_t("");
    m_LastNameIsSet = false;
    m_Phone = utility::conversions::to_string_t("");
    m_PhoneIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_CompanyName = utility::conversions::to_string_t("");
    m_CompanyNameIsSet = false;
    m_Lists = utility::conversions::to_string_t("");
    m_ListsIsSet = false;
    m_Favorited = false;
    m_FavoritedIsSet = false;
    m_Blocked = false;
    m_BlockedIsSet = false;
    m_Type = 0;
    m_TypeIsSet = false;
    m_CustomFieldValuesIsSet = false;
    m_Local = 0;
    m_LocalIsSet = false;
    m_Country = utility::conversions::to_string_t("");
    m_CountryIsSet = false;
    m_TagsIsSet = false;
    m_Owner = 0;
    m_OwnerIsSet = false;
}

UpdateContact_request::~UpdateContact_request()
{
}

void UpdateContact_request::validate()
{
    // TODO: implement validation
}

web::json::value UpdateContact_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_FirstNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("firstName"))] = ModelBase::toJson(m_FirstName);
    }
    if(m_LastNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lastName"))] = ModelBase::toJson(m_LastName);
    }
    if(m_PhoneIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("phone"))] = ModelBase::toJson(m_Phone);
    }
    if(m_EmailIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_CompanyNameIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("companyName"))] = ModelBase::toJson(m_CompanyName);
    }
    if(m_ListsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("lists"))] = ModelBase::toJson(m_Lists);
    }
    if(m_FavoritedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("favorited"))] = ModelBase::toJson(m_Favorited);
    }
    if(m_BlockedIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("blocked"))] = ModelBase::toJson(m_Blocked);
    }
    if(m_TypeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_CustomFieldValuesIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("customFieldValues"))] = ModelBase::toJson(m_CustomFieldValues);
    }
    if(m_LocalIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("local"))] = ModelBase::toJson(m_Local);
    }
    if(m_CountryIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country);
    }
    if(m_TagsIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags);
    }
    if(m_OwnerIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("owner"))] = ModelBase::toJson(m_Owner);
    }

    return val;
}

bool UpdateContact_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("firstName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("firstName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFirstName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFirstName);
            setFirstName(refVal_setFirstName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lastName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lastName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastName);
            setLastName(refVal_setLastName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("phone")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhone;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhone);
            setPhone(refVal_setPhone);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("companyName"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("companyName")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCompanyName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompanyName);
            setCompanyName(refVal_setCompanyName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("lists"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("lists")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLists;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLists);
            setLists(refVal_setLists);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("favorited")));
        if(!fieldValue.is_null())
        {
            bool refVal_setFavorited;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFavorited);
            setFavorited(refVal_setFavorited);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("blocked"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("blocked")));
        if(!fieldValue.is_null())
        {
            bool refVal_setBlocked;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBlocked);
            setBlocked(refVal_setBlocked);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("customFieldValues"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("customFieldValues")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CustomFieldListItem>> refVal_setCustomFieldValues;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomFieldValues);
            setCustomFieldValues(refVal_setCustomFieldValues);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("local"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("local")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLocal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLocal);
            setLocal(refVal_setLocal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::vector<int32_t> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("owner")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setOwner;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOwner);
            setOwner(refVal_setOwner);
            
        }
    }
    return ok;
}

void UpdateContact_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_FirstNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("firstName")), m_FirstName));
    }
    if(m_LastNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lastName")), m_LastName));
    }
    if(m_PhoneIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("phone")), m_Phone));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_CompanyNameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("companyName")), m_CompanyName));
    }
    if(m_ListsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("lists")), m_Lists));
    }
    if(m_FavoritedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("favorited")), m_Favorited));
    }
    if(m_BlockedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("blocked")), m_Blocked));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
    if(m_CustomFieldValuesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("customFieldValues")), m_CustomFieldValues));
    }
    if(m_LocalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("local")), m_Local));
    }
    if(m_CountryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country));
    }
    if(m_TagsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags));
    }
    if(m_OwnerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("owner")), m_Owner));
    }
}

bool UpdateContact_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("firstName"))))
    {
        utility::string_t refVal_setFirstName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("firstName"))), refVal_setFirstName );
        setFirstName(refVal_setFirstName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lastName"))))
    {
        utility::string_t refVal_setLastName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lastName"))), refVal_setLastName );
        setLastName(refVal_setLastName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("phone"))))
    {
        utility::string_t refVal_setPhone;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("phone"))), refVal_setPhone );
        setPhone(refVal_setPhone);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("companyName"))))
    {
        utility::string_t refVal_setCompanyName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("companyName"))), refVal_setCompanyName );
        setCompanyName(refVal_setCompanyName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("lists"))))
    {
        utility::string_t refVal_setLists;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("lists"))), refVal_setLists );
        setLists(refVal_setLists);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))))
    {
        bool refVal_setFavorited;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("favorited"))), refVal_setFavorited );
        setFavorited(refVal_setFavorited);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("blocked"))))
    {
        bool refVal_setBlocked;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("blocked"))), refVal_setBlocked );
        setBlocked(refVal_setBlocked);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        int32_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("customFieldValues"))))
    {
        std::vector<std::shared_ptr<CustomFieldListItem>> refVal_setCustomFieldValues;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("customFieldValues"))), refVal_setCustomFieldValues );
        setCustomFieldValues(refVal_setCustomFieldValues);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("local"))))
    {
        int32_t refVal_setLocal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("local"))), refVal_setLocal );
        setLocal(refVal_setLocal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        utility::string_t refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::vector<int32_t> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("owner"))))
    {
        int32_t refVal_setOwner;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("owner"))), refVal_setOwner );
        setOwner(refVal_setOwner);
    }
    return ok;
}


utility::string_t UpdateContact_request::getFirstName() const
{
    return m_FirstName;
}


void UpdateContact_request::setFirstName(const utility::string_t& value)
{
    m_FirstName = value;
    m_FirstNameIsSet = true;
}

bool UpdateContact_request::firstNameIsSet() const
{
    return m_FirstNameIsSet;
}

void UpdateContact_request::unsetFirstName()
{
    m_FirstNameIsSet = false;
}
utility::string_t UpdateContact_request::getLastName() const
{
    return m_LastName;
}


void UpdateContact_request::setLastName(const utility::string_t& value)
{
    m_LastName = value;
    m_LastNameIsSet = true;
}

bool UpdateContact_request::lastNameIsSet() const
{
    return m_LastNameIsSet;
}

void UpdateContact_request::unsetLastName()
{
    m_LastNameIsSet = false;
}
utility::string_t UpdateContact_request::getPhone() const
{
    return m_Phone;
}


void UpdateContact_request::setPhone(const utility::string_t& value)
{
    m_Phone = value;
    m_PhoneIsSet = true;
}

bool UpdateContact_request::phoneIsSet() const
{
    return m_PhoneIsSet;
}

void UpdateContact_request::unsetPhone()
{
    m_PhoneIsSet = false;
}
utility::string_t UpdateContact_request::getEmail() const
{
    return m_Email;
}


void UpdateContact_request::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool UpdateContact_request::emailIsSet() const
{
    return m_EmailIsSet;
}

void UpdateContact_request::unsetEmail()
{
    m_EmailIsSet = false;
}
utility::string_t UpdateContact_request::getCompanyName() const
{
    return m_CompanyName;
}


void UpdateContact_request::setCompanyName(const utility::string_t& value)
{
    m_CompanyName = value;
    m_CompanyNameIsSet = true;
}

bool UpdateContact_request::companyNameIsSet() const
{
    return m_CompanyNameIsSet;
}

void UpdateContact_request::unsetCompanyName()
{
    m_CompanyNameIsSet = false;
}
utility::string_t UpdateContact_request::getLists() const
{
    return m_Lists;
}


void UpdateContact_request::setLists(const utility::string_t& value)
{
    m_Lists = value;
    m_ListsIsSet = true;
}

bool UpdateContact_request::listsIsSet() const
{
    return m_ListsIsSet;
}

void UpdateContact_request::unsetLists()
{
    m_ListsIsSet = false;
}
bool UpdateContact_request::isFavorited() const
{
    return m_Favorited;
}

void UpdateContact_request::setFavorited(bool value)
{
    m_Favorited = value;
    m_FavoritedIsSet = true;
}

bool UpdateContact_request::favoritedIsSet() const
{
    return m_FavoritedIsSet;
}

void UpdateContact_request::unsetFavorited()
{
    m_FavoritedIsSet = false;
}
bool UpdateContact_request::isBlocked() const
{
    return m_Blocked;
}

void UpdateContact_request::setBlocked(bool value)
{
    m_Blocked = value;
    m_BlockedIsSet = true;
}

bool UpdateContact_request::blockedIsSet() const
{
    return m_BlockedIsSet;
}

void UpdateContact_request::unsetBlocked()
{
    m_BlockedIsSet = false;
}
int32_t UpdateContact_request::getType() const
{
    return m_Type;
}

void UpdateContact_request::setType(int32_t value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool UpdateContact_request::typeIsSet() const
{
    return m_TypeIsSet;
}

void UpdateContact_request::unsetType()
{
    m_TypeIsSet = false;
}
std::vector<std::shared_ptr<CustomFieldListItem>> UpdateContact_request::getCustomFieldValues() const
{
    return m_CustomFieldValues;
}


void UpdateContact_request::setCustomFieldValues(const std::vector<std::shared_ptr<CustomFieldListItem>>& value)
{
    m_CustomFieldValues = value;
    m_CustomFieldValuesIsSet = true;
}

bool UpdateContact_request::customFieldValuesIsSet() const
{
    return m_CustomFieldValuesIsSet;
}

void UpdateContact_request::unsetCustomFieldValues()
{
    m_CustomFieldValuesIsSet = false;
}
int32_t UpdateContact_request::getLocal() const
{
    return m_Local;
}

void UpdateContact_request::setLocal(int32_t value)
{
    m_Local = value;
    m_LocalIsSet = true;
}

bool UpdateContact_request::localIsSet() const
{
    return m_LocalIsSet;
}

void UpdateContact_request::unsetLocal()
{
    m_LocalIsSet = false;
}
utility::string_t UpdateContact_request::getCountry() const
{
    return m_Country;
}


void UpdateContact_request::setCountry(const utility::string_t& value)
{
    m_Country = value;
    m_CountryIsSet = true;
}

bool UpdateContact_request::countryIsSet() const
{
    return m_CountryIsSet;
}

void UpdateContact_request::unsetCountry()
{
    m_CountryIsSet = false;
}
std::vector<int32_t> UpdateContact_request::getTags() const
{
    return m_Tags;
}

void UpdateContact_request::setTags(std::vector<int32_t> value)
{
    m_Tags = value;
    m_TagsIsSet = true;
}

bool UpdateContact_request::tagsIsSet() const
{
    return m_TagsIsSet;
}

void UpdateContact_request::unsetTags()
{
    m_TagsIsSet = false;
}
int32_t UpdateContact_request::getOwner() const
{
    return m_Owner;
}

void UpdateContact_request::setOwner(int32_t value)
{
    m_Owner = value;
    m_OwnerIsSet = true;
}

bool UpdateContact_request::ownerIsSet() const
{
    return m_OwnerIsSet;
}

void UpdateContact_request::unsetOwner()
{
    m_OwnerIsSet = false;
}

}
}
}
}


