/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/UpdateCallbackSettings_request.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

UpdateCallbackSettings_request::UpdateCallbackSettings_request()
{
    m_OutUrl = utility::conversions::to_string_t("");
    m_OutUrlIsSet = false;
    m_InUrl = utility::conversions::to_string_t("");
    m_InUrlIsSet = false;
    m_FormatIsSet = false;
}

UpdateCallbackSettings_request::~UpdateCallbackSettings_request()
{
}

void UpdateCallbackSettings_request::validate()
{
    // TODO: implement validation
}

web::json::value UpdateCallbackSettings_request::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_OutUrlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("outUrl"))] = ModelBase::toJson(m_OutUrl);
    }
    if(m_InUrlIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("inUrl"))] = ModelBase::toJson(m_InUrl);
    }
    if(m_FormatIsSet)
    {   
        
        utility::string_t refVal = fromFormatEnum(m_Format);
        val[utility::conversions::to_string_t(_XPLATSTR("format"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool UpdateCallbackSettings_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("outUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("outUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOutUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOutUrl);
            setOutUrl(refVal_setOutUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("inUrl"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("inUrl")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInUrl);
            setInUrl(refVal_setInUrl);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("format")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFormat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFormat);
            
            setFormat(toFormatEnum(refVal_setFormat));
            
        }
    }
    return ok;
}

void UpdateCallbackSettings_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_OutUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("outUrl")), m_OutUrl));
    }
    if(m_InUrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("inUrl")), m_InUrl));
    }
    if(m_FormatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("format")), fromFormatEnum(m_Format)));
    }
}

bool UpdateCallbackSettings_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("outUrl"))))
    {
        utility::string_t refVal_setOutUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("outUrl"))), refVal_setOutUrl );
        setOutUrl(refVal_setOutUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("inUrl"))))
    {
        utility::string_t refVal_setInUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("inUrl"))), refVal_setInUrl );
        setInUrl(refVal_setInUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        utility::string_t refVal_setFormat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("format"))), refVal_setFormat );
        setFormat(toFormatEnum(refVal_setFormat));
    }
    return ok;
}

UpdateCallbackSettings_request::FormatEnum UpdateCallbackSettings_request::toFormatEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("m")) {
        return FormatEnum::M;
    }
    
    if (value == utility::conversions::to_string_t("u")) {
        return FormatEnum::U;
    }
    
    if (value == utility::conversions::to_string_t("j")) {
        return FormatEnum::J;
    }
    
    throw std::invalid_argument("Invalid value for conversion to FormatEnum");
}


const utility::string_t UpdateCallbackSettings_request::fromFormatEnum(const FormatEnum value) const
{
    switch(value)
    {
        
        case FormatEnum::M: return utility::conversions::to_string_t("m");
        
        case FormatEnum::U: return utility::conversions::to_string_t("u");
        
        case FormatEnum::J: return utility::conversions::to_string_t("j");
        
    }
}


utility::string_t UpdateCallbackSettings_request::getOutUrl() const
{
    return m_OutUrl;
}


void UpdateCallbackSettings_request::setOutUrl(const utility::string_t& value)
{
    m_OutUrl = value;
    m_OutUrlIsSet = true;
}

bool UpdateCallbackSettings_request::outUrlIsSet() const
{
    return m_OutUrlIsSet;
}

void UpdateCallbackSettings_request::unsetOutUrl()
{
    m_OutUrlIsSet = false;
}
utility::string_t UpdateCallbackSettings_request::getInUrl() const
{
    return m_InUrl;
}


void UpdateCallbackSettings_request::setInUrl(const utility::string_t& value)
{
    m_InUrl = value;
    m_InUrlIsSet = true;
}

bool UpdateCallbackSettings_request::inUrlIsSet() const
{
    return m_InUrlIsSet;
}

void UpdateCallbackSettings_request::unsetInUrl()
{
    m_InUrlIsSet = false;
}
UpdateCallbackSettings_request::FormatEnum UpdateCallbackSettings_request::getFormat() const
{
    return m_Format;
}


void UpdateCallbackSettings_request::setFormat(const FormatEnum value)
{
    m_Format = value;
    m_FormatIsSet = true;
}

bool UpdateCallbackSettings_request::formatIsSet() const
{
    return m_FormatIsSet;
}

void UpdateCallbackSettings_request::unsetFormat()
{
    m_FormatIsSet = false;
}

}
}
}
}


