/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/UserStatement.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

UserStatement::UserStatement()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_UserId = 0;
    m_UserIdIsSet = false;
    m_date = utility::datetime();
    m_dateIsSet = false;
    m_Balance = 0.0;
    m_BalanceIsSet = false;
    m_Delta = 0.0f;
    m_DeltaIsSet = false;
    m_Type = utility::conversions::to_string_t("");
    m_TypeIsSet = false;
    m_Value = utility::conversions::to_string_t("");
    m_ValueIsSet = false;
    m_Comment = utility::conversions::to_string_t("");
    m_CommentIsSet = false;
}

UserStatement::~UserStatement()
{
}

void UserStatement::validate()
{
    // TODO: implement validation
}

web::json::value UserStatement::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UserIdIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("userId"))] = ModelBase::toJson(m_UserId);
    }
    if(m_dateIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("date"))] = ModelBase::toJson(m_date);
    }
    if(m_BalanceIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("balance"))] = ModelBase::toJson(m_Balance);
    }
    if(m_DeltaIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("delta"))] = ModelBase::toJson(m_Delta);
    }
    if(m_TypeIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type);
    }
    if(m_ValueIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_CommentIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("comment"))] = ModelBase::toJson(m_Comment);
    }

    return val;
}

bool UserStatement::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("userId")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("date")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDate);
            setDate(refVal_setDate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("balance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("balance")));
        if(!fieldValue.is_null())
        {
            double refVal_setBalance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalance);
            setBalance(refVal_setBalance);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("delta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("delta")));
        if(!fieldValue.is_null())
        {
            float refVal_setDelta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDelta);
            setDelta(refVal_setDelta);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("value")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("comment"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("comment")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setComment;
            ok &= ModelBase::fromJson(fieldValue, refVal_setComment);
            setComment(refVal_setComment);
            
        }
    }
    return ok;
}

void UserStatement::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_UserIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("userId")), m_UserId));
    }
    if(m_dateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("date")), m_date));
    }
    if(m_BalanceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("balance")), m_Balance));
    }
    if(m_DeltaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("delta")), m_Delta));
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("value")), m_Value));
    }
    if(m_CommentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("comment")), m_Comment));
    }
}

bool UserStatement::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("userId"))))
    {
        int32_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("userId"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("date"))))
    {
        utility::datetime refVal_setDate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("date"))), refVal_setDate );
        setDate(refVal_setDate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("balance"))))
    {
        double refVal_setBalance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("balance"))), refVal_setBalance );
        setBalance(refVal_setBalance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("delta"))))
    {
        float refVal_setDelta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("delta"))), refVal_setDelta );
        setDelta(refVal_setDelta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        utility::string_t refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("value"))))
    {
        utility::string_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("comment"))))
    {
        utility::string_t refVal_setComment;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("comment"))), refVal_setComment );
        setComment(refVal_setComment);
    }
    return ok;
}


int32_t UserStatement::getId() const
{
    return m_Id;
}

void UserStatement::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool UserStatement::idIsSet() const
{
    return m_IdIsSet;
}

void UserStatement::unsetId()
{
    m_IdIsSet = false;
}
int32_t UserStatement::getUserId() const
{
    return m_UserId;
}

void UserStatement::setUserId(int32_t value)
{
    m_UserId = value;
    m_UserIdIsSet = true;
}

bool UserStatement::userIdIsSet() const
{
    return m_UserIdIsSet;
}

void UserStatement::unsetUserId()
{
    m_UserIdIsSet = false;
}
utility::datetime UserStatement::getDate() const
{
    return m_date;
}


void UserStatement::setDate(const utility::datetime& value)
{
    m_date = value;
    m_dateIsSet = true;
}

bool UserStatement::dateIsSet() const
{
    return m_dateIsSet;
}

void UserStatement::unsetdate()
{
    m_dateIsSet = false;
}
double UserStatement::getBalance() const
{
    return m_Balance;
}

void UserStatement::setBalance(double value)
{
    m_Balance = value;
    m_BalanceIsSet = true;
}

bool UserStatement::balanceIsSet() const
{
    return m_BalanceIsSet;
}

void UserStatement::unsetBalance()
{
    m_BalanceIsSet = false;
}
float UserStatement::getDelta() const
{
    return m_Delta;
}

void UserStatement::setDelta(float value)
{
    m_Delta = value;
    m_DeltaIsSet = true;
}

bool UserStatement::deltaIsSet() const
{
    return m_DeltaIsSet;
}

void UserStatement::unsetDelta()
{
    m_DeltaIsSet = false;
}
utility::string_t UserStatement::getType() const
{
    return m_Type;
}


void UserStatement::setType(const utility::string_t& value)
{
    m_Type = value;
    m_TypeIsSet = true;
}

bool UserStatement::typeIsSet() const
{
    return m_TypeIsSet;
}

void UserStatement::unsetType()
{
    m_TypeIsSet = false;
}
utility::string_t UserStatement::getValue() const
{
    return m_Value;
}


void UserStatement::setValue(const utility::string_t& value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool UserStatement::valueIsSet() const
{
    return m_ValueIsSet;
}

void UserStatement::unsetValue()
{
    m_ValueIsSet = false;
}
utility::string_t UserStatement::getComment() const
{
    return m_Comment;
}


void UserStatement::setComment(const utility::string_t& value)
{
    m_Comment = value;
    m_CommentIsSet = true;
}

bool UserStatement::commentIsSet() const
{
    return m_CommentIsSet;
}

void UserStatement::unsetComment()
{
    m_CommentIsSet = false;
}

}
}
}
}


