/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "TextMagic/model/UserImage.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

UserImage::UserImage()
{
    m_Href = utility::conversions::to_string_t("");
    m_HrefIsSet = false;
}

UserImage::~UserImage()
{
}

void UserImage::validate()
{
    // TODO: implement validation
}

web::json::value UserImage::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_HrefIsSet)
    {   
        
        val[utility::conversions::to_string_t(_XPLATSTR("href"))] = ModelBase::toJson(m_Href);
    }

    return val;
}

bool UserImage::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("href"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("href")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHref;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHref);
            setHref(refVal_setHref);
            
        }
    }
    return ok;
}

void UserImage::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_HrefIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("href")), m_Href));
    }
}

bool UserImage::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("href"))))
    {
        utility::string_t refVal_setHref;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("href"))), refVal_setHref );
        setHref(refVal_setHref);
    }
    return ok;
}


utility::string_t UserImage::getHref() const
{
    return m_Href;
}


void UserImage::setHref(const utility::string_t& value)
{
    m_Href = value;
    m_HrefIsSet = true;
}

bool UserImage::hrefIsSet() const
{
    return m_HrefIsSet;
}

void UserImage::unsetHref()
{
    m_HrefIsSet = false;
}

}
}
}
}


