/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BadRequestResponse.h
 *
 * Returned when input data validation process has been failed.
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_BadRequestResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_BadRequestResponse_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "TextMagic/model/BadRequestResponse_errors.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class BadRequestResponse_errors;


/// <summary>
/// Returned when input data validation process has been failed.
/// </summary>
class  BadRequestResponse
    : public ModelBase
{
public:
    BadRequestResponse();
    virtual ~BadRequestResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BadRequestResponse members


    /// <summary>
    /// Error code. Meanings of error codes are similar to [HTTP response codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).
    /// </summary>
    int32_t getCode() const;
    bool codeIsSet() const;
    void unsetCode();
    void setCode(int32_t value);

    /// <summary>
    /// Brief error message. You could display this message to your user or save it in a log.
    /// </summary>
    utility::string_t getMessage() const;
    bool messageIsSet() const;
    void unsetMessage();
    void setMessage(const utility::string_t& value);

    std::shared_ptr<BadRequestResponse_errors> getErrors() const;
    bool errorsIsSet() const;
    void unsetErrors();
    void setErrors(const std::shared_ptr<BadRequestResponse_errors>& value);


protected:
    int32_t m_Code;
    bool m_CodeIsSet;

    utility::string_t m_Message;
    bool m_MessageIsSet;

    std::shared_ptr<BadRequestResponse_errors> m_Errors;
    bool m_ErrorsIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_BadRequestResponse_H_ */
