/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ContactCustomField.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_ContactCustomField_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_ContactCustomField_H_


#include "TextMagic/ModelBase.h"

#include "TextMagic/model/UserCustomField.h"
#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

class UserCustomField;


class  ContactCustomField
    : public ModelBase
{
public:
    ContactCustomField();
    virtual ~ContactCustomField();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ContactCustomField members


    utility::string_t getValue() const;
    bool valueIsSet() const;
    void unsetValue();
    void setValue(const utility::string_t& value);

    std::shared_ptr<UserCustomField> getUserCustomField() const;
    bool userCustomFieldIsSet() const;
    void unsetUserCustomField();
    void setUserCustomField(const std::shared_ptr<UserCustomField>& value);


protected:
    utility::string_t m_Value;
    bool m_ValueIsSet;

    std::shared_ptr<UserCustomField> m_UserCustomField;
    bool m_UserCustomFieldIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_ContactCustomField_H_ */
