/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeleteScheduledMessagesBulk_request.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_DeleteScheduledMessagesBulk_request_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_DeleteScheduledMessagesBulk_request_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  DeleteScheduledMessagesBulk_request
    : public ModelBase
{
public:
    DeleteScheduledMessagesBulk_request();
    virtual ~DeleteScheduledMessagesBulk_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DeleteScheduledMessagesBulk_request members


    /// <summary>
    /// Entity ID(s), separated by comma.
    /// </summary>
    utility::string_t getIds() const;
    bool idsIsSet() const;
    void unsetIds();
    void setIds(const utility::string_t& value);

    /// <summary>
    /// Default is 0 (false). If set to 1, all the entities will be removed.
    /// </summary>
    int32_t getAll() const;
    bool allIsSet() const;
    void unsetAll();
    void setAll(int32_t value);

    /// <summary>
    /// Default is an empty string (false). If set, all entities with specified status will be affected.
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const utility::string_t& value);


protected:
    utility::string_t m_Ids;
    bool m_IdsIsSet;

    int32_t m_All;
    bool m_AllIsSet;

    utility::string_t m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_DeleteScheduledMessagesBulk_request_H_ */
