/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DoCarrierLookupResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_DoCarrierLookupResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_DoCarrierLookupResponse_H_

#include <stdexcept>

#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "TextMagic/model/Country.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class Country;


class  DoCarrierLookupResponse
    : public ModelBase
{
public:
    DoCarrierLookupResponse();
    virtual ~DoCarrierLookupResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DoCarrierLookupResponse members

    enum class TypeEnum
    {
        MOBILE,
        LANDLINE,
        VOIP,
    };
    /// <summary>
    /// Phone number type.
    /// </summary>

    TypeEnum toTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromTypeEnum(const TypeEnum value) const;


    /// <summary>
    /// The cost to check that one number is constant – 0.04 in your account currency.
    /// </summary>
    double getCost() const;
    bool costIsSet() const;
    void unsetCost();
    void setCost(double value);

    std::shared_ptr<Country> getCountry() const;
    bool countryIsSet() const;
    void unsetCountry();
    void setCountry(const std::shared_ptr<Country>& value);

    /// <summary>
    /// Phone number in [National format](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers).
    /// </summary>
    utility::string_t getLocal() const;
    bool localIsSet() const;
    void unsetLocal();
    void setLocal(const utility::string_t& value);

    /// <summary>
    /// Phone number type.
    /// </summary>
    TypeEnum getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const TypeEnum value);

    /// <summary>
    /// Carrier name.
    /// </summary>
    utility::string_t getCarrier() const;
    bool carrierIsSet() const;
    void unsetCarrier();
    void setCarrier(const utility::string_t& value);

    /// <summary>
    /// Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
    /// </summary>
    utility::string_t getNumber164() const;
    bool number164IsSet() const;
    void unsetNumber164();
    void setNumber164(const utility::string_t& value);

    /// <summary>
    /// This field shows whether the entered phone number is valid or not.
    /// </summary>
    bool isValid() const;
    bool validIsSet() const;
    void unsetValid();
    void setValid(bool value);


protected:
    double m_Cost;
    bool m_CostIsSet;

    std::shared_ptr<Country> m_Country;
    bool m_CountryIsSet;

    utility::string_t m_Local;
    bool m_LocalIsSet;

    TypeEnum m_Type;
    bool m_TypeIsSet;

    utility::string_t m_Carrier;
    bool m_CarrierIsSet;

    utility::string_t m_Number164;
    bool m_Number164IsSet;

    bool m_Valid;
    bool m_ValidIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_DoCarrierLookupResponse_H_ */
