/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EmailCampaignStatisticTotals.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_EmailCampaignStatisticTotals_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_EmailCampaignStatisticTotals_H_


#include "TextMagic/ModelBase.h"


namespace com {
namespace textmagic {
namespace client {
namespace model {



class  EmailCampaignStatisticTotals
    : public ModelBase
{
public:
    EmailCampaignStatisticTotals();
    virtual ~EmailCampaignStatisticTotals();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EmailCampaignStatisticTotals members


    /// <summary>
    /// Total number of recipients.
    /// </summary>
    int32_t getRecipients() const;
    bool recipientsIsSet() const;
    void unsetRecipients();
    void setRecipients(int32_t value);

    /// <summary>
    /// Number of emails delivered.
    /// </summary>
    int32_t getDelivered() const;
    bool deliveredIsSet() const;
    void unsetDelivered();
    void setDelivered(int32_t value);

    /// <summary>
    /// Number of emails rejected.
    /// </summary>
    int32_t getRejected() const;
    bool rejectedIsSet() const;
    void unsetRejected();
    void setRejected(int32_t value);

    /// <summary>
    /// Number of emails failed to send.
    /// </summary>
    int32_t getFailed() const;
    bool failedIsSet() const;
    void unsetFailed();
    void setFailed(int32_t value);

    /// <summary>
    /// Number of emails opened.
    /// </summary>
    int32_t getOpened() const;
    bool openedIsSet() const;
    void unsetOpened();
    void setOpened(int32_t value);

    /// <summary>
    /// Number of emails with clicks.
    /// </summary>
    int32_t getClicked() const;
    bool clickedIsSet() const;
    void unsetClicked();
    void setClicked(int32_t value);

    /// <summary>
    /// Number of spam reports.
    /// </summary>
    int32_t getSpamReports() const;
    bool spamReportsIsSet() const;
    void unsetSpamReports();
    void setSpamReports(int32_t value);

    /// <summary>
    /// Number of unsubscribes.
    /// </summary>
    int32_t getUnsubscribed() const;
    bool unsubscribedIsSet() const;
    void unsetUnsubscribed();
    void setUnsubscribed(int32_t value);


protected:
    int32_t m_Recipients;
    bool m_RecipientsIsSet;

    int32_t m_Delivered;
    bool m_DeliveredIsSet;

    int32_t m_Rejected;
    bool m_RejectedIsSet;

    int32_t m_Failed;
    bool m_FailedIsSet;

    int32_t m_Opened;
    bool m_OpenedIsSet;

    int32_t m_Clicked;
    bool m_ClickedIsSet;

    int32_t m_SpamReports;
    bool m_SpamReportsIsSet;

    int32_t m_Unsubscribed;
    bool m_UnsubscribedIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_EmailCampaignStatisticTotals_H_ */
