/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FileMetadataPreview.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_FileMetadataPreview_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_FileMetadataPreview_H_


#include "TextMagic/ModelBase.h"


namespace com {
namespace textmagic {
namespace client {
namespace model {



class  FileMetadataPreview
    : public ModelBase
{
public:
    FileMetadataPreview();
    virtual ~FileMetadataPreview();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// FileMetadataPreview members


    int32_t getHeight() const;
    bool heightIsSet() const;
    void unsetHeight();
    void setHeight(int32_t value);

    int32_t getWidth() const;
    bool widthIsSet() const;
    void unsetWidth();
    void setWidth(int32_t value);


protected:
    int32_t m_Height;
    bool m_HeightIsSet;

    int32_t m_Width;
    bool m_WidthIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_FileMetadataPreview_H_ */
