/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetBalanceNotificationOptionsResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_GetBalanceNotificationOptionsResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_GetBalanceNotificationOptionsResponse_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  GetBalanceNotificationOptionsResponse
    : public ModelBase
{
public:
    GetBalanceNotificationOptionsResponse();
    virtual ~GetBalanceNotificationOptionsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetBalanceNotificationOptionsResponse members


    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR1() const;
    bool r1IsSet() const;
    void unsetr_1();
    void setR1(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR2() const;
    bool r2IsSet() const;
    void unsetr_2();
    void setR2(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR3() const;
    bool r3IsSet() const;
    void unsetr_3();
    void setR3(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR5() const;
    bool r5IsSet() const;
    void unsetr_5();
    void setR5(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR10() const;
    bool r10IsSet() const;
    void unsetr_10();
    void setR10(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR20() const;
    bool r20IsSet() const;
    void unsetr_20();
    void setR20(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR30() const;
    bool r30IsSet() const;
    void unsetr_30();
    void setR30(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR50() const;
    bool r50IsSet() const;
    void unsetr_50();
    void setR50(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR100() const;
    bool r100IsSet() const;
    void unsetr_100();
    void setR100(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR500() const;
    bool r500IsSet() const;
    void unsetr_500();
    void setR500(const utility::string_t& value);

    /// <summary>
    /// Contains sign of currency in Unicode hex code.
    /// </summary>
    utility::string_t getR1000() const;
    bool r1000IsSet() const;
    void unsetr_1000();
    void setR1000(const utility::string_t& value);


protected:
    utility::string_t m_r_1;
    bool m_r_1IsSet;

    utility::string_t m_r_2;
    bool m_r_2IsSet;

    utility::string_t m_r_3;
    bool m_r_3IsSet;

    utility::string_t m_r_5;
    bool m_r_5IsSet;

    utility::string_t m_r_10;
    bool m_r_10IsSet;

    utility::string_t m_r_20;
    bool m_r_20IsSet;

    utility::string_t m_r_30;
    bool m_r_30IsSet;

    utility::string_t m_r_50;
    bool m_r_50IsSet;

    utility::string_t m_r_100;
    bool m_r_100IsSet;

    utility::string_t m_r_500;
    bool m_r_500IsSet;

    utility::string_t m_r_1000;
    bool m_r_1000IsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_GetBalanceNotificationOptionsResponse_H_ */
