/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetEmailSendersResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_GetEmailSendersResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_GetEmailSendersResponse_H_


#include "TextMagic/ModelBase.h"

#include <vector>
#include "TextMagic/model/EmailSenderItem.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class EmailSenderItem;


class  GetEmailSendersResponse
    : public ModelBase
{
public:
    GetEmailSendersResponse();
    virtual ~GetEmailSendersResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetEmailSendersResponse members


    /// <summary>
    /// Array of email sender objects.
    /// </summary>
    std::vector<std::shared_ptr<EmailSenderItem>> getItems() const;
    bool itemsIsSet() const;
    void unsetItems();
    void setItems(const std::vector<std::shared_ptr<EmailSenderItem>>& value);


protected:
    std::vector<std::shared_ptr<EmailSenderItem>> m_Items;
    bool m_ItemsIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_GetEmailSendersResponse_H_ */
