/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GetMessagePriceResponseCountriesItem.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponseCountriesItem_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponseCountriesItem_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  GetMessagePriceResponseCountriesItem
    : public ModelBase
{
public:
    GetMessagePriceResponseCountriesItem();
    virtual ~GetMessagePriceResponseCountriesItem();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// GetMessagePriceResponseCountriesItem members


    /// <summary>
    /// The 2-letter ISO country code.
    /// </summary>
    utility::string_t getCountry() const;
    bool countryIsSet() const;
    void unsetCountry();
    void setCountry(const utility::string_t& value);

    /// <summary>
    /// Country name.
    /// </summary>
    utility::string_t getCountryName() const;
    bool countryNameIsSet() const;
    void unsetCountryName();
    void setCountryName(const utility::string_t& value);

    /// <summary>
    /// Is allowed to use a dedicated number?
    /// </summary>
    bool isAllowDedicated() const;
    bool allowDedicatedIsSet() const;
    void unsetAllowDedicated();
    void setAllowDedicated(bool value);

    /// <summary>
    /// Parts count to send.
    /// </summary>
    double getCount() const;
    bool countIsSet() const;
    void unsetCount();
    void setCount(double value);

    /// <summary>
    /// Maximum parts to send.
    /// </summary>
    double getMax() const;
    bool maxIsSet() const;
    void unsetMax();
    void setMax(double value);

    /// <summary>
    /// Total price to send.
    /// </summary>
    utility::string_t getSum() const;
    bool sumIsSet() const;
    void unsetSum();
    void setSum(const utility::string_t& value);

    /// <summary>
    /// Is this a landline number?
    /// </summary>
    double getLandline() const;
    bool landlineIsSet() const;
    void unsetLandline();
    void setLandline(double value);


protected:
    utility::string_t m_Country;
    bool m_CountryIsSet;

    utility::string_t m_CountryName;
    bool m_CountryNameIsSet;

    bool m_AllowDedicated;
    bool m_AllowDedicatedIsSet;

    double m_Count;
    bool m_CountIsSet;

    double m_Max;
    bool m_MaxIsSet;

    utility::string_t m_Sum;
    bool m_SumIsSet;

    double m_Landline;
    bool m_LandlineIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_GetMessagePriceResponseCountriesItem_H_ */
