/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MessageOut.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_MessageOut_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_MessageOut_H_

#include <stdexcept>

#include "TextMagic/ModelBase.h"

#include "TextMagic/model/MessageOut_senderSource.h"
#include "TextMagic/model/MessageOut_session.h"
#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {

class MessageOut_senderSource;
class MessageOut_session;


class  MessageOut
    : public ModelBase
{
public:
    MessageOut();
    virtual ~MessageOut();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MessageOut members

    enum class StatusEnum
    {
        Q,
        S,
        E,
        R,
        A,
        D,
        B,
        F,
        U,
        J,
        I,
        P,
        H,
    };
    /// <summary>
    /// Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. 
    /// </summary>
    enum class RejectReasonEnum
    {
        A,
        F,
        L,
        C,
        U,
        B,
        S,
        M,
        N,
        I,
        IF,
        D,
        T,
        E,
        H,
        K,
        R,
        G,
        J,
        W,
        V,
        Q,
        X,
        O,
        P,
    };
    /// <summary>
    /// Rejection reason.
    /// </summary>

    StatusEnum toStatusEnum(const utility::string_t& value) const;
    const utility::string_t fromStatusEnum(const StatusEnum value) const;


    RejectReasonEnum toRejectReasonEnum(const utility::string_t& value) const;
    const utility::string_t fromRejectReasonEnum(const RejectReasonEnum value) const;


    /// <summary>
    /// Message ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Message sender (phone number or alphanumeric Sender ID).
    /// </summary>
    utility::string_t getSender() const;
    bool senderIsSet() const;
    void unsetSender();
    void setSender(const utility::string_t& value);

    /// <summary>
    /// Recipient&#x60;s phone number.
    /// </summary>
    utility::string_t getReceiver() const;
    bool receiverIsSet() const;
    void unsetReceiver();
    void setReceiver(const utility::string_t& value);

    utility::string_t getText() const;
    bool textIsSet() const;
    void unsetText();
    void setText(const utility::string_t& value);

    /// <summary>
    /// Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. 
    /// </summary>
    StatusEnum getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const StatusEnum value);

    /// <summary>
    /// Rejection reason.
    /// </summary>
    RejectReasonEnum getRejectReason() const;
    bool rejectReasonIsSet() const;
    void unsetRejectReason();
    void setRejectReason(const RejectReasonEnum value);

    /// <summary>
    /// Recipient contact ID.
    /// </summary>
    int32_t getContactId() const;
    bool contactIdIsSet() const;
    void unsetContactId();
    void setContactId(int32_t value);

    /// <summary>
    /// Message Session ID of a message.
    /// </summary>
    int32_t getSessionId() const;
    bool sessionIdIsSet() const;
    void unsetSessionId();
    void setSessionId(int32_t value);

    /// <summary>
    /// Sending time.
    /// </summary>
    utility::datetime getMessageTime() const;
    bool messageTimeIsSet() const;
    void unsetMessageTime();
    void setMessageTime(const utility::datetime& value);

    utility::string_t getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();
    void setAvatar(const utility::string_t& value);

    /// <summary>
    /// Indicates that the message has been deleted.
    /// </summary>
    bool isDeleted() const;
    bool deletedIsSet() const;
    void unsetDeleted();
    void setDeleted(bool value);

    /// <summary>
    /// Message charset. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS. 
    /// </summary>
    utility::string_t getCharset() const;
    bool charsetIsSet() const;
    void unsetCharset();
    void setCharset(const utility::string_t& value);

    /// <summary>
    /// Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. 
    /// </summary>
    utility::string_t getCharsetLabel() const;
    bool charsetLabelIsSet() const;
    void unsetCharsetLabel();
    void setCharsetLabel(const utility::string_t& value);

    /// <summary>
    /// Contact first name. Could be substituted from your [Contacts](https://docs.textmagic.com/#tag/Contacts) (even if you submitted the phone number instead of the contact ID). 
    /// </summary>
    utility::string_t getFirstName() const;
    bool firstNameIsSet() const;
    void unsetFirstName();
    void setFirstName(const utility::string_t& value);

    /// <summary>
    /// Contact last name.
    /// </summary>
    utility::string_t getLastName() const;
    bool lastNameIsSet() const;
    void unsetLastName();
    void setLastName(const utility::string_t& value);

    /// <summary>
    /// The 2-letter ISO country code of the recipient&#39;s phone number. 
    /// </summary>
    utility::string_t getCountry() const;
    bool countryIsSet() const;
    void unsetCountry();
    void setCountry(const utility::string_t& value);

    /// <summary>
    /// Receipent&#x60;s phone number.
    /// </summary>
    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    /// <summary>
    /// Message price.
    /// </summary>
    float getPrice() const;
    bool priceIsSet() const;
    void unsetPrice();
    void setPrice(float value);

    /// <summary>
    /// Message parts (multiples of 160 characters) count.
    /// </summary>
    int32_t getPartsCount() const;
    bool partsCountIsSet() const;
    void unsetPartsCount();
    void setPartsCount(int32_t value);

    /// <summary>
    /// The user email which this message came from. For Email2SMS and Distribution Lists the messages, it is an original email address - in other cases, it is an account email address.
    /// </summary>
    utility::string_t getFromEmail() const;
    bool fromEmailIsSet() const;
    void unsetFromEmail();
    void setFromEmail(const utility::string_t& value);

    /// <summary>
    /// The Phone number used to send the SMS.
    /// </summary>
    utility::string_t getFromNumber() const;
    bool fromNumberIsSet() const;
    void unsetFromNumber();
    void setFromNumber(const utility::string_t& value);

    std::shared_ptr<MessageOut_senderSource> getSenderSource() const;
    bool senderSourceIsSet() const;
    void unsetSenderSource();
    void setSenderSource(const std::shared_ptr<MessageOut_senderSource>& value);

    std::shared_ptr<MessageOut_session> getSession() const;
    bool sessionIsSet() const;
    void unsetSession();
    void setSession(const std::shared_ptr<MessageOut_session>& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Sender;
    bool m_SenderIsSet;

    utility::string_t m_Receiver;
    bool m_ReceiverIsSet;

    utility::string_t m_Text;
    bool m_TextIsSet;

    StatusEnum m_Status;
    bool m_StatusIsSet;

    RejectReasonEnum m_RejectReason;
    bool m_RejectReasonIsSet;

    int32_t m_ContactId;
    bool m_ContactIdIsSet;

    int32_t m_SessionId;
    bool m_SessionIdIsSet;

    utility::datetime m_MessageTime;
    bool m_MessageTimeIsSet;

    utility::string_t m_Avatar;
    bool m_AvatarIsSet;

    bool m_Deleted;
    bool m_DeletedIsSet;

    utility::string_t m_Charset;
    bool m_CharsetIsSet;

    utility::string_t m_CharsetLabel;
    bool m_CharsetLabelIsSet;

    utility::string_t m_FirstName;
    bool m_FirstNameIsSet;

    utility::string_t m_LastName;
    bool m_LastNameIsSet;

    utility::string_t m_Country;
    bool m_CountryIsSet;

    utility::string_t m_Phone;
    bool m_PhoneIsSet;

    float m_Price;
    bool m_PriceIsSet;

    int32_t m_PartsCount;
    bool m_PartsCountIsSet;

    utility::string_t m_FromEmail;
    bool m_FromEmailIsSet;

    utility::string_t m_FromNumber;
    bool m_FromNumberIsSet;

    std::shared_ptr<MessageOut_senderSource> m_SenderSource;
    bool m_SenderSourceIsSet;

    std::shared_ptr<MessageOut_session> m_Session;
    bool m_SessionIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_MessageOut_H_ */
