/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MessageTemplate.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_MessageTemplate_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_MessageTemplate_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  MessageTemplate
    : public ModelBase
{
public:
    MessageTemplate();
    virtual ~MessageTemplate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MessageTemplate members


    /// <summary>
    /// Template ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// Template name.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    /// <summary>
    /// Template text. May contain dynamic fields inside braces. See the [Custom fields list](https://docs.textmagic.com/#tag/Templates/Custom-fields-list-(Merge-dynamic-fields)).
    /// </summary>
    utility::string_t getContent() const;
    bool contentIsSet() const;
    void unsetContent();
    void setContent(const utility::string_t& value);

    /// <summary>
    /// Time when the template was last modified.
    /// </summary>
    utility::datetime getLastModified() const;
    bool lastModifiedIsSet() const;
    void unsetLastModified();
    void setLastModified(const utility::datetime& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_Content;
    bool m_ContentIsSet;

    utility::datetime m_LastModified;
    bool m_LastModifiedIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_MessageTemplate_H_ */
