/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MessagesIcs.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_MessagesIcs_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_MessagesIcs_H_

#include <stdexcept>

#include "TextMagic/ModelBase.h"

#include "TextMagic/model/MessagesIcs_parameters.h"
#include "TextMagic/model/MessagesIcs_textParameters.h"
#include <cpprest/details/basic_types.h>
#include "TextMagic/model/MessageSession.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class MessageSession;
class MessagesIcs_parameters;
class MessagesIcs_textParameters;


class  MessagesIcs
    : public ModelBase
{
public:
    MessagesIcs();
    virtual ~MessagesIcs();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MessagesIcs members

    enum class TypeEnum
    {
        ONCE,
        HOURLY,
        DAILY,
        WEEKLY,
        MONTHLY,
        YEARLY,
    };

    TypeEnum toTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromTypeEnum(const TypeEnum value) const;


    /// <summary>
    /// Schedule ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// The next send date in [ISO 8601](https://en.wikipedia.org/?title&#x3D;ISO_8601) format. 
    /// </summary>
    utility::datetime getNextSend() const;
    bool nextSendIsSet() const;
    void unsetNextSend();
    void setNextSend(const utility::datetime& value);

    /// <summary>
    /// [iCal RRULE](http://www.kanzaki.com/docs/ical/rrule.html) string. 
    /// </summary>
    utility::string_t getRrule() const;
    bool rruleIsSet() const;
    void unsetRrule();
    void setRrule(const utility::string_t& value);

    std::shared_ptr<MessageSession> getSession() const;
    bool sessionIsSet() const;
    void unsetSession();
    void setSession(const std::shared_ptr<MessageSession>& value);

    /// <summary>
    /// The date and time when the last message was sent.
    /// </summary>
    utility::datetime getLastSent() const;
    bool lastSentIsSet() const;
    void unsetLastSent();
    void setLastSent(const utility::datetime& value);

    /// <summary>
    /// Aggregated contact information. If the message was scheduled to be sent to a single contact, a full name will be returned here. Otherwise, a total amount of contacts will be returned.
    /// </summary>
    utility::string_t getContactName() const;
    bool contactNameIsSet() const;
    void unsetContactName();
    void setContactName(const utility::string_t& value);

    std::shared_ptr<MessagesIcs_parameters> getParameters() const;
    bool parametersIsSet() const;
    void unsetParameters();
    void setParameters(const std::shared_ptr<MessagesIcs_parameters>& value);

    TypeEnum getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const TypeEnum value);

    /// <summary>
    /// A human-readable summary of the sending schedule.
    /// </summary>
    utility::string_t getSummary() const;
    bool summaryIsSet() const;
    void unsetSummary();
    void setSummary(const utility::string_t& value);

    std::shared_ptr<MessagesIcs_textParameters> getTextParameters() const;
    bool textParametersIsSet() const;
    void unsetTextParameters();
    void setTextParameters(const std::shared_ptr<MessagesIcs_textParameters>& value);

    /// <summary>
    /// First occurence date.
    /// </summary>
    utility::datetime getFirstOccurrence() const;
    bool firstOccurrenceIsSet() const;
    void unsetFirstOccurrence();
    void setFirstOccurrence(const utility::datetime& value);

    /// <summary>
    /// Last occurence date (could be &#x60;null&#x60; if the schedule is endless).
    /// </summary>
    utility::datetime getLastOccurrence() const;
    bool lastOccurrenceIsSet() const;
    void unsetLastOccurrence();
    void setLastOccurrence(const utility::datetime& value);

    /// <summary>
    /// Amount of actual recipients.
    /// </summary>
    int32_t getRecipientsCount() const;
    bool recipientsCountIsSet() const;
    void unsetRecipientsCount();
    void setRecipientsCount(int32_t value);

    /// <summary>
    /// User-friendly timezone name (with spaces replaced by underscores).
    /// </summary>
    utility::string_t getTimezone() const;
    bool timezoneIsSet() const;
    void unsetTimezone();
    void setTimezone(const utility::string_t& value);

    /// <summary>
    /// Indicates that scheduling has been completed.
    /// </summary>
    bool isCompleted() const;
    bool completedIsSet() const;
    void unsetCompleted();
    void setCompleted(bool value);

    /// <summary>
    /// A relative link to the contact avatar.
    /// </summary>
    utility::string_t getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();
    void setAvatar(const utility::string_t& value);

    /// <summary>
    /// Scheduling creation time.
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::datetime m_NextSend;
    bool m_NextSendIsSet;

    utility::string_t m_Rrule;
    bool m_RruleIsSet;

    std::shared_ptr<MessageSession> m_Session;
    bool m_SessionIsSet;

    utility::datetime m_LastSent;
    bool m_LastSentIsSet;

    utility::string_t m_ContactName;
    bool m_ContactNameIsSet;

    std::shared_ptr<MessagesIcs_parameters> m_Parameters;
    bool m_ParametersIsSet;

    TypeEnum m_Type;
    bool m_TypeIsSet;

    utility::string_t m_Summary;
    bool m_SummaryIsSet;

    std::shared_ptr<MessagesIcs_textParameters> m_TextParameters;
    bool m_TextParametersIsSet;

    utility::datetime m_FirstOccurrence;
    bool m_FirstOccurrenceIsSet;

    utility::datetime m_LastOccurrence;
    bool m_LastOccurrenceIsSet;

    int32_t m_RecipientsCount;
    bool m_RecipientsCountIsSet;

    utility::string_t m_Timezone;
    bool m_TimezoneIsSet;

    bool m_Completed;
    bool m_CompletedIsSet;

    utility::string_t m_Avatar;
    bool m_AvatarIsSet;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_MessagesIcs_H_ */
