/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MuteChatsBulk_request.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_MuteChatsBulk_request_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_MuteChatsBulk_request_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  MuteChatsBulk_request
    : public ModelBase
{
public:
    MuteChatsBulk_request();
    virtual ~MuteChatsBulk_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// MuteChatsBulk_request members


    /// <summary>
    /// Entity ID(s), separated by comma.
    /// </summary>
    utility::string_t getIds() const;
    bool idsIsSet() const;
    void unsetIds();
    void setIds(const utility::string_t& value);

    /// <summary>
    /// Entity ID(s), separated by comma
    /// </summary>
    bool isAll() const;
    bool allIsSet() const;
    void unsetAll();
    void setAll(bool value);

    /// <summary>
    /// Mute for N hours.
    /// </summary>
    int32_t getRFor() const;
    bool rForIsSet() const;
    void unsetr_for();
    void setRFor(int32_t value);


protected:
    utility::string_t m_Ids;
    bool m_IdsIsSet;

    bool m_All;
    bool m_AllIsSet;

    int32_t m_r_for;
    bool m_r_forIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_MuteChatsBulk_request_H_ */
