/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResourceLinkResponse.h
 *
 * Response contains paginated list of data items.
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_ResourceLinkResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_ResourceLinkResponse_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



/// <summary>
/// Response contains paginated list of data items.
/// </summary>
class  ResourceLinkResponse
    : public ModelBase
{
public:
    ResourceLinkResponse();
    virtual ~ResourceLinkResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ResourceLinkResponse members


    /// <summary>
    /// Resource ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// A link to this resource. If you want to fetch it, just **GET** this address.
    /// </summary>
    utility::string_t getHref() const;
    bool hrefIsSet() const;
    void unsetHref();
    void setHref(const utility::string_t& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Href;
    bool m_HrefIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_ResourceLinkResponse_H_ */
