/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ScheduleEmailCampaignResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_ScheduleEmailCampaignResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_ScheduleEmailCampaignResponse_H_


#include "TextMagic/ModelBase.h"

#include "TextMagic/model/ScheduledEmailCampaignDetails.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class ScheduledEmailCampaignDetails;


class  ScheduleEmailCampaignResponse
    : public ModelBase
{
public:
    ScheduleEmailCampaignResponse();
    virtual ~ScheduleEmailCampaignResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ScheduleEmailCampaignResponse members


    std::shared_ptr<ScheduledEmailCampaignDetails> getCampaign() const;
    bool campaignIsSet() const;
    void unsetCampaign();
    void setCampaign(const std::shared_ptr<ScheduledEmailCampaignDetails>& value);

    /// <summary>
    /// Estimated cost for sending this campaign.
    /// </summary>
    float getCost() const;
    bool costIsSet() const;
    void unsetCost();
    void setCost(float value);


protected:
    std::shared_ptr<ScheduledEmailCampaignDetails> m_Campaign;
    bool m_CampaignIsSet;

    float m_Cost;
    bool m_CostIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_ScheduleEmailCampaignResponse_H_ */
