/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendPhoneVerificationCodeResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_SendPhoneVerificationCodeResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_SendPhoneVerificationCodeResponse_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  SendPhoneVerificationCodeResponse
    : public ModelBase
{
public:
    SendPhoneVerificationCodeResponse();
    virtual ~SendPhoneVerificationCodeResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendPhoneVerificationCodeResponse members


    /// <summary>
    /// The ID of a verification request. This is required to finish the verification request in the next step.
    /// </summary>
    utility::string_t getVerifyId() const;
    bool verifyIdIsSet() const;
    void unsetVerifyId();
    void setVerifyId(const utility::string_t& value);

    /// <summary>
    /// An amount of credit which will be deducted from your account balance when this verification is successfully completed.
    /// </summary>
    double getPrice() const;
    bool priceIsSet() const;
    void unsetPrice();
    void setPrice(double value);


protected:
    utility::string_t m_VerifyId;
    bool m_VerifyIdIsSet;

    double m_Price;
    bool m_PriceIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_SendPhoneVerificationCodeResponse_H_ */
