/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SendMessageResponse.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_SendMessageResponse_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_SendMessageResponse_H_

#include <stdexcept>

#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  SendMessageResponse
    : public ModelBase
{
public:
    SendMessageResponse();
    virtual ~SendMessageResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SendMessageResponse members

    enum class TypeEnum
    {
        MESSAGE,
        SESSION,
        SCHEDULE,
        BULK,
    };
    /// <summary>
    /// Message response type: * **message** – when the message is sent to a single recipient. * **session** – when the message is sent is to multiple recipients. * **schedule** - when the message is scheduled for sending. * **bulk** - when the message is sent to multiple recipients and the number of recipients requires asynchronous processing See [Sending more than 1,000 messages in one session](https://docs.textmagic.com/#section/Tutorials/Sending-more-than-1000-messages-in-one-session). 
    /// </summary>

    TypeEnum toTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromTypeEnum(const TypeEnum value) const;


    /// <summary>
    /// Message ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// URI of the message session.
    /// </summary>
    utility::string_t getHref() const;
    bool hrefIsSet() const;
    void unsetHref();
    void setHref(const utility::string_t& value);

    /// <summary>
    /// Message response type: * **message** – when the message is sent to a single recipient. * **session** – when the message is sent is to multiple recipients. * **schedule** - when the message is scheduled for sending. * **bulk** - when the message is sent to multiple recipients and the number of recipients requires asynchronous processing See [Sending more than 1,000 messages in one session](https://docs.textmagic.com/#section/Tutorials/Sending-more-than-1000-messages-in-one-session). 
    /// </summary>
    TypeEnum getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const TypeEnum value);

    /// <summary>
    /// Message session ID.
    /// </summary>
    int32_t getSessionId() const;
    bool sessionIdIsSet() const;
    void unsetSessionId();
    void setSessionId(int32_t value);

    /// <summary>
    /// Bulk Session ID. See [Sending more than 1,000 messages in one session](https://docs.textmagic.com/#section/Tutorials/Sending-more-than-1000-messages-in-one-session).
    /// </summary>
    int32_t getBulkId() const;
    bool bulkIdIsSet() const;
    void unsetBulkId();
    void setBulkId(int32_t value);

    /// <summary>
    /// Message ID.
    /// </summary>
    int32_t getMessageId() const;
    bool messageIdIsSet() const;
    void unsetMessageId();
    void setMessageId(int32_t value);

    /// <summary>
    /// Message Schedule ID.
    /// </summary>
    int32_t getScheduleId() const;
    bool scheduleIdIsSet() const;
    void unsetScheduleId();
    void setScheduleId(int32_t value);

    /// <summary>
    /// Message Chat ID.
    /// </summary>
    int32_t getChatId() const;
    bool chatIdIsSet() const;
    void unsetChatId();
    void setChatId(int32_t value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Href;
    bool m_HrefIsSet;

    TypeEnum m_Type;
    bool m_TypeIsSet;

    int32_t m_SessionId;
    bool m_SessionIdIsSet;

    int32_t m_BulkId;
    bool m_BulkIdIsSet;

    int32_t m_MessageId;
    bool m_MessageIdIsSet;

    int32_t m_ScheduleId;
    bool m_ScheduleIdIsSet;

    int32_t m_ChatId;
    bool m_ChatIdIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_SendMessageResponse_H_ */
