/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SurveySenderCountries.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_SurveySenderCountries_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_SurveySenderCountries_H_


#include "TextMagic/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace textmagic {
namespace client {
namespace model {



class  SurveySenderCountries
    : public ModelBase
{
public:
    SurveySenderCountries();
    virtual ~SurveySenderCountries();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// SurveySenderCountries members


    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    utility::string_t getCountryName() const;
    bool countryNameIsSet() const;
    void unsetCountryName();
    void setCountryName(const utility::string_t& value);

    utility::string_t getFromNumber() const;
    bool fromNumberIsSet() const;
    void unsetFromNumber();
    void setFromNumber(const utility::string_t& value);

    /// <summary>
    /// Is allowed to use a dedicated number?
    /// </summary>
    bool isAllowDedicated() const;
    bool allowDedicatedIsSet() const;
    void unsetAllowDedicated();
    void setAllowDedicated(bool value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_CountryName;
    bool m_CountryNameIsSet;

    utility::string_t m_FromNumber;
    bool m_FromNumberIsSet;

    bool m_AllowDedicated;
    bool m_AllowDedicatedIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_SurveySenderCountries_H_ */
