/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateChatDesktopNotificationSettings_request.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_UpdateChatDesktopNotificationSettings_request_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_UpdateChatDesktopNotificationSettings_request_H_


#include "TextMagic/ModelBase.h"


namespace com {
namespace textmagic {
namespace client {
namespace model {



class  UpdateChatDesktopNotificationSettings_request
    : public ModelBase
{
public:
    UpdateChatDesktopNotificationSettings_request();
    virtual ~UpdateChatDesktopNotificationSettings_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateChatDesktopNotificationSettings_request members


    /// <summary>
    /// Enable notification sound?
    /// </summary>
    bool isPlaySound() const;
    bool playSoundIsSet() const;
    void unsetPlaySound();
    void setPlaySound(bool value);

    /// <summary>
    /// Show desktop notifications about new messages.
    /// </summary>
    bool isShowNotifications() const;
    bool showNotificationsIsSet() const;
    void unsetShowNotifications();
    void setShowNotifications(bool value);

    /// <summary>
    /// Incoming message text will be displayed in desktop notifications.
    /// </summary>
    bool isShowText() const;
    bool showTextIsSet() const;
    void unsetShowText();
    void setShowText(bool value);

    /// <summary>
    /// Sound Id of a notification.
    /// </summary>
    int32_t getSoundId() const;
    bool soundIdIsSet() const;
    void unsetSoundId();
    void setSoundId(int32_t value);


protected:
    bool m_PlaySound;
    bool m_PlaySoundIsSet;

    bool m_ShowNotifications;
    bool m_ShowNotificationsIsSet;

    bool m_ShowText;
    bool m_ShowTextIsSet;

    int32_t m_SoundId;
    bool m_SoundIdIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_UpdateChatDesktopNotificationSettings_request_H_ */
