/**
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.17.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User.h
 *
 * 
 */

#ifndef COM_TEXTMAGIC_CLIENT_MODEL_User_H_
#define COM_TEXTMAGIC_CLIENT_MODEL_User_H_

#include <stdexcept>

#include "TextMagic/ModelBase.h"

#include "TextMagic/model/UserImage.h"
#include <cpprest/details/basic_types.h>
#include "TextMagic/model/Timezone.h"
#include "TextMagic/model/Country.h"
#include "TextMagic/model/Currency.h"

namespace com {
namespace textmagic {
namespace client {
namespace model {

class Currency;
class Country;
class Timezone;
class UserImage;


class  User
    : public ModelBase
{
public:
    User();
    virtual ~User();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// User members

    enum class DisplayTimeFormatEnum
    {
        _12H,
        _24H,
    };
    /// <summary>
    /// User&#39;s preferred format of time display: * *12h* - AM/PM format; * *24h* - 24-hour clock format. 
    /// </summary>
    enum class StatusEnum
    {
        A,
        T,
    };
    /// <summary>
    /// Current account status: * **A** for Active; * **T** for Trial. 
    /// </summary>
    enum class SubaccountTypeEnum
    {
        P,
        A,
        U,
    };
    /// <summary>
    /// Type of account: * **P** for Parent User; * **A** for Administrator Sub-Account; * **U** for Regular User. 
    /// </summary>

    DisplayTimeFormatEnum toDisplayTimeFormatEnum(const utility::string_t& value) const;
    const utility::string_t fromDisplayTimeFormatEnum(const DisplayTimeFormatEnum value) const;


    StatusEnum toStatusEnum(const utility::string_t& value) const;
    const utility::string_t fromStatusEnum(const StatusEnum value) const;


    SubaccountTypeEnum toSubaccountTypeEnum(const utility::string_t& value) const;
    const utility::string_t fromSubaccountTypeEnum(const SubaccountTypeEnum value) const;


    /// <summary>
    /// User ID.
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(int32_t value);

    /// <summary>
    /// User&#39;s preferred format of time display: * *12h* - AM/PM format; * *24h* - 24-hour clock format. 
    /// </summary>
    DisplayTimeFormatEnum getDisplayTimeFormat() const;
    bool displayTimeFormatIsSet() const;
    void unsetDisplayTimeFormat();
    void setDisplayTimeFormat(const DisplayTimeFormatEnum value);

    /// <summary>
    /// Username.
    /// </summary>
    utility::string_t getUsername() const;
    bool usernameIsSet() const;
    void unsetUsername();
    void setUsername(const utility::string_t& value);

    /// <summary>
    /// Account first name.
    /// </summary>
    utility::string_t getFirstName() const;
    bool firstNameIsSet() const;
    void unsetFirstName();
    void setFirstName(const utility::string_t& value);

    /// <summary>
    /// Account last name.
    /// </summary>
    utility::string_t getLastName() const;
    bool lastNameIsSet() const;
    void unsetLastName();
    void setLastName(const utility::string_t& value);

    /// <summary>
    /// User email address.
    /// </summary>
    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    /// <summary>
    /// Current account status: * **A** for Active; * **T** for Trial. 
    /// </summary>
    StatusEnum getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const StatusEnum value);

    /// <summary>
    /// Account balance (in account currency).
    /// </summary>
    double getBalance() const;
    bool balanceIsSet() const;
    void unsetBalance();
    void setBalance(double value);

    /// <summary>
    /// User&#39;s phone number.
    /// </summary>
    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    /// <summary>
    /// Account company name.
    /// </summary>
    utility::string_t getCompany() const;
    bool companyIsSet() const;
    void unsetCompany();
    void setCompany(const utility::string_t& value);

    std::shared_ptr<Currency> getCurrency() const;
    bool currencyIsSet() const;
    void unsetCurrency();
    void setCurrency(const std::shared_ptr<Currency>& value);

    std::shared_ptr<Country> getCountry() const;
    bool countryIsSet() const;
    void unsetCountry();
    void setCountry(const std::shared_ptr<Country>& value);

    std::shared_ptr<Timezone> getTimezone() const;
    bool timezoneIsSet() const;
    void unsetTimezone();
    void setTimezone(const std::shared_ptr<Timezone>& value);

    /// <summary>
    /// Type of account: * **P** for Parent User; * **A** for Administrator Sub-Account; * **U** for Regular User. 
    /// </summary>
    SubaccountTypeEnum getSubaccountType() const;
    bool subaccountTypeIsSet() const;
    void unsetSubaccountType();
    void setSubaccountType(const SubaccountTypeEnum value);

    /// <summary>
    /// Does the account have a confirmed email?
    /// </summary>
    bool isEmailAccepted() const;
    bool emailAcceptedIsSet() const;
    void unsetEmailAccepted();
    void setEmailAccepted(bool value);

    /// <summary>
    /// Does the account have a confirmed phone number?
    /// </summary>
    bool isPhoneAccepted() const;
    bool phoneAcceptedIsSet() const;
    void unsetPhoneAccepted();
    void setPhoneAccepted(bool value);

    std::shared_ptr<UserImage> getAvatar() const;
    bool avatarIsSet() const;
    void unsetAvatar();
    void setAvatar(const std::shared_ptr<UserImage>& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;

    DisplayTimeFormatEnum m_DisplayTimeFormat;
    bool m_DisplayTimeFormatIsSet;

    utility::string_t m_Username;
    bool m_UsernameIsSet;

    utility::string_t m_FirstName;
    bool m_FirstNameIsSet;

    utility::string_t m_LastName;
    bool m_LastNameIsSet;

    utility::string_t m_Email;
    bool m_EmailIsSet;

    StatusEnum m_Status;
    bool m_StatusIsSet;

    double m_Balance;
    bool m_BalanceIsSet;

    utility::string_t m_Phone;
    bool m_PhoneIsSet;

    utility::string_t m_Company;
    bool m_CompanyIsSet;

    std::shared_ptr<Currency> m_Currency;
    bool m_CurrencyIsSet;

    std::shared_ptr<Country> m_Country;
    bool m_CountryIsSet;

    std::shared_ptr<Timezone> m_Timezone;
    bool m_TimezoneIsSet;

    SubaccountTypeEnum m_SubaccountType;
    bool m_SubaccountTypeIsSet;

    bool m_EmailAccepted;
    bool m_EmailAcceptedIsSet;

    bool m_PhoneAccepted;
    bool m_PhoneAcceptedIsSet;

    std::shared_ptr<UserImage> m_Avatar;
    bool m_AvatarIsSet;

};


}
}
}
}

#endif /* COM_TEXTMAGIC_CLIENT_MODEL_User_H_ */
